### ISSUE TITLE
Since we treat numbers as strings, display order display is now off

### ISSUE THREAD

**Issue by cmontella** [witheve/Eve#170]
Sorting for number goes alphabetically, meaning an order like this:

1, 10, 100, 11, 12, 13, 14, 15, 16, 17, 18, 19, 2, 20, 21, ... etc

**Comment by jakedowns** [comment]
This is still happening for me after walking through the negation tutorial. Could it be stale import data in the artists.eve save file?

![](https://s3.amazonaws.com/f.cl.ly/items/153e3L0i3H3m233a2r12/Image%202015-10-29%20at%2010.46.49%20PM.png)
