### ISSUE TITLE
run.sh: line 26: multirust: command not found

### ISSUE THREAD

**Issue by jhftrifork** [witheve/Eve#181]
```
> sh run.sh
~/dev/Eve ~/dev/Eve
~/dev/Eve
~/dev/Eve ~/dev/Eve
run.sh: line 26: multirust: command not found
```

It was not obvious to me that I first had to run `./install-multirust.sh`. This should be in the quickstart instructions, or a call to it should be made from `run.sh`.

**Comment by frewsxcv** [comment]
I also ran into this

**Comment by dmorehouse** [comment]
Running ./install-multirust.sh fixed this issue for me as well.

**Comment by jamii** [comment]
I'm not sure that running global installs without asking is a good idea, but we can document it and add a warning to run.sh
