### ISSUE TITLE
UI: Error message separate from error location

### ISSUE THREAD

**Issue by RubenSandwich** [witheve/Eve#182]
When trying to save a file, the error message is separate from the error location. This can easily be missed and lead to confusion especially with a disappearing message. The error message should be close to the error location in order to grab the attention of the user and inform them that there is a problem. (Screenshot kept small to fit in discussion panel, but bigger screens only exacerbate this issue.)

![Image of error message separate from error location](http://rubennic.com/static/img/seperateError.png)

**Comment by joshuafcole** [comment]
Yep, we need to add feedback to validated form fields.
