### ISSUE TITLE
UI: Popover tabs change popover origin

### ISSUE THREAD

**Issue by RubenSandwich** [witheve/Eve#184]
On the settings popover when changing tabs, for example from 'Save' to 'Load', the popovers vertical position changes. This increases the amount of distance a user has to move in order get back to there original tab and also creates a jarring effect as the popover snaps into a new location and the user needs to reorient themselves.

**Comment by joshuafcole** [comment]
This is caused by us using a style to naively center the modal. I suppose we could stretch all modals to a min-height to mitigate the problem. Did you have a particular fix in mind?

**Comment by RubenSandwich** [comment]
I actually don't think there is a great fix for this problem so I'll outline some I've seen and what I believe are their Pros and Cons.

1 - Enforce a minimum height to each modal:  
- Pros:  
  - Uniform height  
  - Universal origin  
- Cons:  
  - Uniform height  
  - Potential for lots of wasted real estate 

2 - Use average height of all modals to define origin:  
- Pros:  
  - No wasted real estate  
  - Universal origin  
- Cons:  
  - Not perfectly centered 
  - Origin needs to change with each modal change

3 - Animate height changes but keep first origin:  
- Pros:  
  - No wasted real estate  
  - Universal origin
- Cons:  
  - Not perfectly centered (Tends to be even worse then #2.)
  - Added animation

I personally prefer option 2, but they are not without their faults.

**Comment by joshuafcole** [comment]
Your second solution makes sense as well. I don't have a strong preference between that and the first. If this doesn't get picked up in the next couple days I'll choose an approach and add it in.

**Comment by rschroll** [comment]
I think (2) is the right solution, and it's aided by an additional wrinkle: The optical center of a canvas (the point that draws the eye best) is not in the center of the canvas, but slightly above.  Things that are exactly centered often appear to be too low.  (If you go look at the nearest door, you'll probably find that the bottom hinge is further from the bottom than the top hinge is from the top.  But it looks right.)

We can use this to our advantage.  We don't want the dialog to be exactly centered -- we want it a bit above the geometrical center.  We don't need an exact proportion, so we can pick something that looks pretty good for most dialogs.

#245 is my particular choice of location.  But it's an inexact science, so feel free to adjust the numbers until you find something you like.
