### ISSUE TITLE
Crash on New / Delete

### ISSUE THREAD

**Issue by dmorehouse** [witheve/Eve#189]
Running the latest (61d074c74547aba9ec8406ade11995207202f7d9), whenever I try to use the New / Delete button my server crashes.  I modified my run.sh to add --verbose flag to the cargo launch.

RSNPLALTM80s-MacBook-Pro:Eve dmorehouse$ ./run.sh --debug
~/dev/Eve ~/dev/Eve
~/dev/Eve
~/dev/Eve ~/dev/Eve
multirust: using existing install for 'nightly-2015-08-10'
multirust: override toolchain for '/Users/dmorehouse/dev/Eve/runtime' set to 'nightly-2015-08-10'
       Fresh winapi-build v0.1.0
       Fresh httparse v0.1.5
       Fresh unicase v0.1.0
       Fresh typeable v0.1.2
       Fresh language-tags v0.0.7
       Fresh bitflags v0.3.2
       Fresh traitobject v0.0.1
       Fresh lazy_static v0.1.12
       Fresh winapi v0.2.1
       Fresh bit-vec v0.4.1
       Fresh byteorder v0.3.11
       Fresh matches v0.1.2
       Fresh rustc-serialize v0.3.15
       Fresh pkg-config v0.3.5
       Fresh gcc v0.3.11
       Fresh libc v0.1.8
       Fresh bit-set v0.2.0
       Fresh cbor v0.3.14
       Fresh conduit-mime-types v0.7.3
       Fresh url v0.2.36
       Fresh rand v0.3.8
       Fresh log v0.3.1
       Fresh num_cpus v0.2.6
       Fresh mime v0.0.12
       Fresh hpack v0.2.0
       Fresh kernel32-sys v0.1.3
       Fresh openssl-sys v0.6.4
       Fresh solicit v0.4.0
       Fresh time v0.1.31
       Fresh openssl v0.6.4
       Fresh cookie v0.1.21
       Fresh hyper v0.6.5
       Fresh websocket v0.12.2
       Fresh eve v0.0.1 (file:///Users/dmorehouse/dev/Eve/runtime)
     Running `target/debug/server`
reading saved state took 1.1416777790000197s
Connection from 127.0.0.1:52440
Connection from 127.0.0.1:52447
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 22, message: "Invalid argument" } }', ../src/libcore/result.rs:732
stack backtrace:
   1:        0x10698d395 - sys::backtrace::write::h6ddc342d792b0e00eys
   2:        0x106990a10 - panicking::on_panic::h958ebf4d6905d53emex
   3:        0x106980d92 - rt::unwind::begin_unwind_inner::hbd872a23a0e4a7d76Hw
   4:        0x1069813ec - rt::unwind::begin_unwind_fmt::h6cb11d09fc9699d1cHw
   5:        0x1069903dc - rust_begin_unwind
   6:        0x1069b3c35 - panicking::panic_fmt::hbcb2030cdfd213bbTgC
   7:        0x10679d430 - result::Result<T, E>::unwrap::h15762084798196596601
   8:        0x10679c477 - server::send_event::ha9409291829be6cck4k
   9:        0x1067bb9f8 - server::handle_event::h0fa63162401f05e7Icl
  10:        0x1067bf1f4 - server::run::h6e76fd49812d796cKil
  11:        0x1065d71aa - main::haf3dba23e5e43d0aiaa
  12:        0x10699033d - __rust_try
  13:        0x1069916ad - rt::lang_start::ha6eaa4ada71a9cdbh9w
  14:        0x1065dbf1e - main
Process didn't exit successfully: `target/debug/server` (exit code: 101)

**Comment by ibdknox** [comment]
Try removing runtime/autosave

**Comment by ibdknox** [comment]
We can't seem to repro the issue and the error you're getting is particularly weird. The only place we call unwrap is when we try to get the address of the socket.

**Comment by jamii** [comment]
Weird ... that's crashing at `sender.get_mut().peer_addr().unwrap()` - getting the address of the client socket.

**Comment by dmorehouse** [comment]
How do I remove runtime/autosave?

**Comment by joshuafcole** [comment]
Please do the following to get us some more information on this:
1. Recompile the server in debug mode `./run.sh --debug` to see if we can get any additional information from rust.
2. Delete your autosave `rm ./runtime/autosave` to ensure we're starting from a blank slate.
3. Type  DEBUG.SEND = DEBUG.RECEIVE = 3 in the console prior to pressing the new button.
4. Press the new button and paste us both the output from your terminal and in your console.

Thanks for the help!

**Comment by dmorehouse** [comment]
Still happens after rm -rf runtime/autosave with the following crash
RSNPLALTM80s-MacBook-Pro:Eve dmorehouse$ ./run.sh --debug
~/dev/Eve ~/dev/Eve
~/dev/Eve
~/dev/Eve ~/dev/Eve
multirust: using existing install for 'nightly-2015-08-10'
multirust: override toolchain for '/Users/dmorehouse/dev/Eve/runtime' set to 'nightly-2015-08-10'
       Fresh libc v0.1.8
       ...
       Fresh eve v0.0.1 (file:///Users/dmorehouse/dev/Eve/runtime)
     Running `target/debug/server`
reading saved state took 0.00029840299976058304s
Connection from 127.0.0.1:52746
Connection from 127.0.0.1:52754
Send error: WebSocketError: I/O failure
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 22, message: "Invalid argument" } }', ../src/libcore/result.rs:732
stack backtrace:
   1:        0x10d05b395 - sys::backtrace::write::h6ddc342d792b0e00eys
   2:        0x10d05ea10 - panicking::on_panic::h958ebf4d6905d53emex
   3:        0x10d04ed92 - rt::unwind::begin_unwind_inner::hbd872a23a0e4a7d76Hw
   4:        0x10d04f3ec - rt::unwind::begin_unwind_fmt::h6cb11d09fc9699d1cHw
   5:        0x10d05e3dc - rust_begin_unwind
   6:        0x10d081c35 - panicking::panic_fmt::hbcb2030cdfd213bbTgC
   7:        0x10ce6b430 - result::Result<T, E>::unwrap::h15762084798196596601
   8:        0x10ce6a477 - server::send_event::ha9409291829be6cck4k
   9:        0x10ce899f8 - server::handle_event::h0fa63162401f05e7Icl
  10:        0x10ce8d1f4 - server::run::h6e76fd49812d796cKil
  11:        0x10cca51aa - main::haf3dba23e5e43d0aiaa
  12:        0x10d05e33d - __rust_try
  13:        0x10d05f6ad - rt::lang_start::ha6eaa4ada71a9cdbh9w
  14:        0x10cca9f1e - main
Process didn't exit successfully: `target/debug/server` (exit code: 101)
~/dev/Eve

**Comment by dmorehouse** [comment]
Console Output
============
DEBUG.SEND = DEBUG.RECEIVE = 3
3
[client:sent][+6/-0]                                                                                            15:23:09
  field +1/-0
   inserts field: view,field: field,field: kind
(index)0120"beba6eee-df7c-4ec2-a2e1-574d2457dab6""214a0889-9d4f-418d-9ba5-84420d4b0cd8""output"
   removes field: view,field: field,field: kind
Array[0]length: 0__proto__: Array[0]
  tag +1/-0
   inserts tag: view,tag: tag
(index)010"beba6eee-df7c-4ec2-a2e1-574d2457dab6""editor"
   removes tag: view,tag: tag
  display name +2/-0
   inserts display name: id,display name: name
(index)010"beba6eee-df7c-4ec2-a2e1-574d2457dab6""New table!"1"214a0889-9d4f-418d-9ba5-84420d4b0cd8""Field A"
   removes display name: id,display name: name
  view +1/-0
   inserts view: view,view: kind
(index)010"beba6eee-df7c-4ec2-a2e1-574d2457dab6""table"
   removes view: view,view: kind
Array[0]length: 0__proto__: Array[0]
  display order +1/-0
   inserts display order: id,display order: priority
(index)010"214a0889-9d4f-418d-9ba5-84420d4b0cd8"-1
   removes display order: id,display order: priority
WebSocket connection to 'ws://localhost:2794/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

Terminal Output
============
RSNPLALTM80s-MacBook-Pro:Eve dmorehouse$ ./run.sh --debug
~/dev/Eve ~/dev/Eve
~/dev/Eve
~/dev/Eve ~/dev/Eve
multirust: using existing install for 'nightly-2015-08-10'
multirust: override toolchain for '/Users/dmorehouse/dev/Eve/runtime' set to 'nightly-2015-08-10'
       Fresh unicase v0.1.0
       Fresh typeable v0.1.2
       Fresh language-tags v0.0.7
       Fresh byteorder v0.3.11
       Fresh bit-vec v0.4.1
       Fresh lazy_static v0.1.12
       Fresh bitflags v0.3.2
       Fresh traitobject v0.0.1
       Fresh winapi-build v0.1.0
       Fresh winapi v0.2.1
       Fresh matches v0.1.2
       Fresh gcc v0.3.11
       Fresh rustc-serialize v0.3.15
       Fresh pkg-config v0.3.5
       Fresh httparse v0.1.5
       Fresh libc v0.1.8
       Fresh bit-set v0.2.0
       Fresh url v0.2.36
       Fresh conduit-mime-types v0.7.3
       Fresh cbor v0.3.14
       Fresh num_cpus v0.2.6
       Fresh rand v0.3.8
       Fresh log v0.3.1
       Fresh hpack v0.2.0
       Fresh mime v0.0.12
       Fresh kernel32-sys v0.1.3
       Fresh openssl-sys v0.6.4
       Fresh solicit v0.4.0
       Fresh time v0.1.31
       Fresh openssl v0.6.4
       Fresh cookie v0.1.21
       Fresh hyper v0.6.5
       Fresh websocket v0.12.2
       Fresh eve v0.0.1 (file:///Users/dmorehouse/dev/Eve/runtime)
     Running `target/debug/server`
reading saved state took 0.9591443830140634s
Connection from 127.0.0.1:53623
Connection from 127.0.0.1:53649
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 22, message: "Invalid argument" } }', ../src/libcore/result.rs:732
stack backtrace:
   1:        0x1100ec395 - sys::backtrace::write::h6ddc342d792b0e00eys
   2:        0x1100efa10 - panicking::on_panic::h958ebf4d6905d53emex
   3:        0x1100dfd92 - rt::unwind::begin_unwind_inner::hbd872a23a0e4a7d76Hw
   4:        0x1100e03ec - rt::unwind::begin_unwind_fmt::h6cb11d09fc9699d1cHw
   5:        0x1100ef3dc - rust_begin_unwind
   6:        0x110112c35 - panicking::panic_fmt::hbcb2030cdfd213bbTgC
   7:        0x10fefc430 - result::Result<T, E>::unwrap::h15762084798196596601
   8:        0x10fefb477 - server::send_event::ha9409291829be6cck4k
   9:        0x10ff1a9f8 - server::handle_event::h0fa63162401f05e7Icl
  10:        0x10ff1e1f4 - server::run::h6e76fd49812d796cKil
  11:        0x10fd361aa - main::haf3dba23e5e43d0aiaa
  12:        0x1100ef33d - __rust_try
  13:        0x1100f06ad - rt::lang_start::ha6eaa4ada71a9cdbh9w
  14:        0x10fd3af1e - main
Process didn't exit successfully: `target/debug/server` (exit code: 101)
~/dev/Eve

**Comment by joshuafcole** [comment]
It looks like you may have had two waiting rooms open at once.
```
Connection from 127.0.0.1:53623
Connection from 127.0.0.1:53649
```
This shouldn't be a problem (I've tried to test it exhaustively), but its plausible that there may be a race condition at work here. Can you please close all existing waiting rooms and try again? The script will open a fresh one for you. The nominal result for a single waiting room open should look something like this:

```
Connection from 127.0.0.1:51198
Received close message from 127.0.0.1:51198.
Closing connection from 127.0.0.1:51198...
Connection from 127.0.0.1:51198 has closed successfully.
Connection from 127.0.0.1:51205
```

**Comment by jamii** [comment]
There are some race conditions in the session handling. We aren't even using sessions right now so I'm just going to strip them out entirely for now.
