### ISSUE TITLE
Unable to run eve

### ISSUE THREAD

**Issue by JannKleen** [witheve/Eve#190]
Fails when trying to run on OS X 10.10.4 (rust and multirust installed with homebrew)

Any other useful information I can provide?

```
multirust: using existing install for 'nightly-2015-08-10'
multirust: override toolchain for '/Users/jann/Development/Eve/runtime' set to 'nightly-2015-08-10'
   Compiling openssl-sys v0.6.4
   Compiling kernel32-sys v0.1.3
Build failed, waiting for other jobs to finish...
failed to run custom build command for `openssl-sys v0.6.4`
Process didn't exit successfully: `/Users/jann/Development/Eve/runtime/target/release/build/openssl-sys-765ddf9de3c5179c/build-script-build` (signal: 5)
--- stderr
dyld: Library not loaded: x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib/libstd-35017696.dylib
  Referenced from: /Users/jann/Development/Eve/runtime/target/release/build/openssl-sys-765ddf9de3c5179c/build-script-build
  Reason: image not found
```

**Comment by ibdknox** [comment]
Try 
```
brew install openssl
```

**Comment by JannKleen** [comment]
thanks for the quick reply but: :disappointed: 

```
brew install openssl
Warning: openssl-1.0.2d_1 already installed
```

**Comment by sherbondy** [comment]
Hi, I ran into this issue too. Are you on 10.11?
This fixed it for me:
```
brew unlink openssl
brew link openssl --force
```

Reason:
["openssl is keg-only and must be linked with --force"](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/FAQ.md#what-does-keg-only-mean)

If you do `brew info openssl` you get more helpful advice:
```
Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include
```

Maybe the build script for Even on Mac OS could be adjusted to accommodate for this.

OpenSSL is chock-full of vulnerabilities :( Need to carefully track which version you're using once Eve enters wider production use:
https://www.openssl.org/news/vulnerabilities.html

**Comment by joshuafcole** [comment]
Unfortunately we don't have much control over that. We actually don't use OpenSSL directly at all, it's a sub-dependency of one of the network IO crates we use (either websockets or hyper, I can't recall). We'll do our best to keep an eye out though.

**Comment by steveklabnik** [comment]
https://github.com/sfackler/rust-openssl/tree/master/openssl-sys would be where this happens.

**Comment by sherbondy** [comment]
Oh sweet, so we can locally adjust these ENV vars just while installing Eve to use the desired version of OpenSSL?

```
OPENSSL_LIB_DIR - If specified, a directory that will be used to find OpenSSL runtime libraries.
OPENSSL_INCLUDE_DIR - If specified, a directory that will be used to find OpenSSL headers.
OPENSSL_STATIC - If specified, OpenSSL libraries will be statically rather than dynamically linked.
If either OPENSSL_LIB_DIR or OPENSSL_INCLUDE_DIR are specified, then the build script will skip the pkg-config step.
```

**Comment by steveklabnik** [comment]
Yes, I believe so.

**Comment by joshuafcole** [comment]
@JannKleen Please let us know if @sherbondy's fix worked for you. If so we'll close the issue and add it to the getting started guide (with an appropriate warning and an explanation of how to link against other versions of OpenSSL).

**Comment by JannKleen** [comment]
@joshuafcole I think (without knowing really anything about rust) that the problem might be at a different place ... now I get ```failed to run custom build command for `kernel32-sys v0.1.3``` and sometimes the old ```failed to run custom build command for `openssl-sys v0.6.4````
I'm suspecting the 'actual' error message is ```dyld: Library not loaded: x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib/libstd-35017696.dylib```

But I could be totally wrong as well! :smile:

**Comment by groovy354** [comment]
@sherbondy What should I set these ENV vars to?

**Comment by JannKleen** [comment]
@groovy354 (assuming you're on a Mac using Homebrew) first run
```
brew unlink openssl
brew link openssl --force
```
and then run the following command (not sure if OPENSSL_STATIC=1 is needed):
```
OPENSSL_LIB_DIR=/usr/local/opt/openssl/lib OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include OPENSSL_STATIC=1 ./run.sh
```

**Comment by JannKleen** [comment]
ok after a quite a while of trying and reading i figured out a bit about rust ;)
running the following in ```runtime/``` works (also be sure to install multirust with the ```--HEAD``` option if you want to use the homebrew version):
```
OPENSSL_LIB_DIR=/usr/local/opt/openssl/lib OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include cargo build```

then ```run.sh``` works as expected 
@joshuafcole @sherbondy thanks for the help!
