### ISSUE TITLE
No such file or directory tsc

### ISSUE THREAD

**Issue by mythmon** [witheve/Eve#197]
I suspect this is a problem from using a relative entry in $PATH?

```
$ which tsc
node_modules/.bin/tsc

$ tsc
Version 1.5.3
Syntax:   tsc [options] [file ...]

Examples: tsc hello.ts
<snip>

$ ./run.sh
* Checking dependencies...
~/tmp/Eve ~/tmp/Eve
* Compiling Editor...
./run.sh: line 23: node_modules/.bin/tsc: No such file or directory
Failed to compile editor, bailing.
~/tmp/Eve
```

**Comment by joshuafcole** [comment]
Yes. We need to change directory during the installation process. The tsc command is called in the ui subdirectory. Try using an absolute path and you should be fine.

**Comment by joshuafcole** [comment]
If you're still having issues,please comment again and I'll reopen the issue for debugging.

**Comment by mythmon** [comment]
Switching to an absolute path works fine. This is the first time I've run into such a problem though. Kind of odd.
