### ISSUE TITLE
blastoff: empty temp dir

### ISSUE THREAD

**Issue by nidu** [witheve/Eve#199]
Hello,

After launching `.\install-multirust.sh` on windows with cmder (i guess it's cygwin) or git bash i get following:

```
Welcome to Git (version 1.8.3-preview20130601)


Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.

This script will download, build, and install multirust as root, then
configure multirust with the most common options.  It may prompt for
your password for installation via 'sudo'.

You may run /usr/local/lib/rustlib/uninstall.sh to uninstall multirust.

blastoff: empty temp dir
```

So multirust is not installed and `.\run.sh` doesn't want to launch the app. Am i missing something?

**Comment by joshuafcole** [comment]
Unfortunately multirust isn't supported on windows yet. We're working on a proper install script for windows users that does not rely on multirust. That's why run.sh won't run. Also it looks like you're using git-bash from git-scm rather than cygwin.
