### ISSUE TITLE
Aws ec-2 instance

### ISSUE THREAD

**Issue by ghost** [witheve/Eve#203]
I have installed  Eve on Aws instance.

Should I be passing any flags  such as port, no browser?

What should be appended to the instance url?  /8080/editor or something else?

The server dies as soon as I try anything unfortunately.

**Comment by ibdknox** [comment]
We haven't done much work to make Eve hostable yet, so I'm not sure what will break. In theory, you need to make port 8080 accessible and then you'd go to:

http://aws-ip-address:8080/editor

**Comment by joshuafcole** [comment]
Please let us know if you run into any other issues doing so (with stack traces and any other information you can provide) and we'll do what we can to support you.

**Comment by prstockton** [comment]
Thanks for the fast reply Chris.

Just for the record: Ubuntu 14.04 

The app is actually visible at the url but there is a message at the top to say that the server is dead.

Terminal output appended below:

ubuntu@ip-172-31-32-105:~/Eve$ ./run.sh
* Checking dependencies...
~/Eve ~/Eve
* Compiling Editor...
~/Eve
* Opening /home/ubuntu/Eve/ui/waiting-room.html
~/Eve ~/Eve
* Updating rust if necessary...
./run.sh: line 37: xdg-open: command not found
multirust: using existing install for 'nightly-2015-08-10'
multirust: override toolchain for '/home/ubuntu/Eve/runtime' set to 'nightly-2015-08-10'
* Compiling server... (This takes a while)
     Running `target/debug/server`
reading saved state took 0.00012652499981413712s

Running ./run.sh --debug:

ubuntu@ip-172-31-32-105:~/Eve$ ./run.sh --debug
* Checking dependencies...
~/Eve ~/Eve
* Compiling Editor...
~/Eve
* Opening /home/ubuntu/Eve/ui/waiting-room.html
~/Eve ~/Eve
* Updating rust if necessary...
./run.sh: line 37: xdg-open: command not found
multirust: using existing install for 'nightly-2015-08-10'
multirust: override toolchain for '/home/ubuntu/Eve/runtime' set to 'nightly-2015-08-10'
* Compiling server... (This takes a while)
   Compiling pkg-config v0.3.5
   Compiling matches v0.1.2
   Compiling rustc-serialize v0.3.15
   Compiling traitobject v0.0.1
   Compiling bit-vec v0.4.1
   Compiling libc v0.1.8
   Compiling winapi-build v0.1.0
   Compiling language-tags v0.0.7
   Compiling bitflags v0.3.2
   Compiling gcc v0.3.11
   Compiling byteorder v0.3.11
   Compiling typeable v0.1.2
   Compiling lazy_static v0.1.12
   Compiling unicase v0.1.0
   Compiling winapi v0.2.1
   Compiling httparse v0.1.5
   Compiling conduit-mime-types v0.7.3
   Compiling url v0.2.36
   Compiling bit-set v0.2.0
   Compiling rand v0.3.8
   Compiling num_cpus v0.2.6
   Compiling log v0.3.1
   Compiling kernel32-sys v0.1.3
   Compiling openssl-sys v0.6.4
   Compiling cbor v0.3.14
   Compiling hpack v0.2.0
   Compiling mime v0.0.12
   Compiling solicit v0.4.0
   Compiling time v0.1.31
   Compiling openssl v0.6.4
   Compiling cookie v0.1.21
   Compiling hyper v0.6.5
   Compiling websocket v0.12.2
   Compiling eve v0.0.1 (file:///home/ubuntu/Eve/runtime)
     Running `target/release/server`
reading saved state took 0.000023724999891783227s

Xdg wants to open a file on the installed browser presumably? 

If there is anything that you want me to try or report back on just let me know.

**Comment by joshuafcole** [comment]
Yep, xdg-open relies on having some sort of desktop manager installed to open files based on mime type. I'll add in a detection flag and a warning so it doesn't pollute the logs of people using Eve remotely.

Are you running the latest stable eve? There was a bug that had a similar result for other users that has since been fixed. Please also paste the crash log from the server after you attempted to connect if the problem persists.
