### ISSUE TITLE
thread '<unnamed>' panicked at 'Cannot serve '

### ISSUE THREAD

**Issue by solarisfire** [witheve/Eve#205]
Fresh install of Ubuntu 14.04.3 (Fully updated with apt-get).
Installed npm (nodejs).
Installed typescript.
Installed git.
Installed multirust.
ln -s /usr/bin/nodejs /usr/bin/node
installed xdg-utils
./run.sh

Everything seems to start up fine.

Navigate to http://localhost:8080 in browser:

    thread '<unnamed>' panicked at 'Cannot serve ', src/login.rs:283
    stack backtrace:
       1:     0x7fd1c84ad8ce - sys::backtrace::write::h7f613ce09e7b1d1d5As
       2:     0x7fd1c84b1166 - panicking::on_panic::he6322b413efd100fGFx
       3:     0x7fd1c84a069e - rt::unwind::begin_unwind_inner::h16a4850d896eee23R6w
       4:     0x7fd1c84a10c6 - rt::unwind::begin_unwind_fmt::hc997fb3d79d46a00X5w
       5:     0x7fd1c824bc21 - login::login::h34cb70ceb54785ddQwk
                        at /home/solarisfire/Eve-master/runtime/<std macros>:8
       6:     0x7fd1c82227b5 - fn(hyper..server..request..Request, hyper..server..response..Response<hyper..net..Fresh>) $u7b$login..login$u7d$::fn_pointer_shim.22931::h59bb7664e8d0500d
       7:     0x7fd1c8222710 - server::F.Handler::handle::h11463059438850624518
                        at /home/solarisfire/.multirust/toolchains/nightly-2015-08-10/cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.6.5/src/server/mod.rs:353
       8:     0x7fd1c820667c - server::Worker<'a, H>::keep_alive_loop::h9145447074920620363
                        at /home/solarisfire/.multirust/toolchains/nightly-2015-08-10/cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.6.5/src/server/mod.rs:271
       9:     0x7fd1c82018a7 - server::Worker<'a, H>::handle_connection::h214925591338452996
                        at /home/solarisfire/.multirust/toolchains/nightly-2015-08-10/cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.6.5/src/server/mod.rs:232
      10:     0x7fd1c8200f5b - server::with_listener::closure.21881
                        at /home/solarisfire/.multirust/toolchains/nightly-2015-08-10/cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.6.5/src/server/mod.rs:203
      11:     0x7fd1c823b922 - server::listener::spawn_with::closure.23674
                        at /home/solarisfire/.multirust/toolchains/nightly-2015-08-10/cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.6.5/src/server/listener.rs:51
      12:     0x7fd1c823b6fd - boxed::F.FnBox<A>::call_box::h2768780049709748440
                        at ../src/liballoc/boxed.rs:515
      13:     0x7fd1c8231340 - boxed::Box<FnBox<A, Output $u3d$$u20$R$GT$$u2b$$u20$Send$u20$$u2b$$u20$$u27$a$GT$.FnOnce$LT$A$GT$::call_once::h11419360599757575757
                        at ../src/liballoc/boxed.rs:531
      14:     0x7fd1c8230df2 - thread::Builder::spawn_inner::closure.23255
                        at ../src/libstd/thread/mod.rs:322
      15:     0x7fd1c8230d6e - rt::unwind::try::try_fn::h12215222090687763496
                        at ../src/libstd/rt/unwind/mod.rs:168
      16:     0x7fd1c84b0a8d - __rust_try
      17:     0x7fd1c84ab7e7 - rt::unwind::try::inner_try::hd1ccb4243958898cK2w
      18:     0x7fd1c8230cb8 - rt::unwind::try::h10846001478860874452
                        at ../src/libstd/rt/unwind/mod.rs:140
      19:     0x7fd1c8230b1e - thread::Builder::spawn_inner::closure.23207
                        at ../src/libstd/thread/mod.rs:322
      20:     0x7fd1c82316bd - boxed::F.FnBox<A>::call_box::h11401848262299269194
                        at ../src/liballoc/boxed.rs:515
      21:     0x7fd1c84afc31 - sys::thread::Thread::new::thread_start::h7245c58ce67341f49bw
      22:     0x7fd1c6b91181 - start_thread
      23:     0x7fd1c73ab47c - __clone
      24:                0x0 - <unknown>

**Comment by ibdknox** [comment]
Definitely a bug, but I think it'll work if you go to http://localhost:8080/editor

**Comment by joshuafcole** [comment]
I can't reproduce this by accessing locally or remotely. Just to clarify, are you on latest?

**Comment by cmontella** [comment]
Will fix... the URL needs a default page

**Comment by cmontella** [comment]
Fixed

**Comment by solarisfire** [comment]
Awesome. Cheers guys! :D
