### ISSUE TITLE
Communication Exploration

### ISSUE THREAD

**Issue by joshuafcole** [witheve/Eve#216]
Investigate ways communication primitives can simplify development

**Comment by cmontella** [comment]
Here's an idea: maybe we should have a short ~1-2 page deliverable for research tasks like this. It will help us build our case as to the decisions we made and the alternatives available. It could include what's out there, whose done what, how did that work for them, recommendation, a list of papers or whatever else.

**Comment by ibdknox** [comment]
Sounds like a good idea. How about researchy tasks result in the first pass at a design document detailing this stuff.

**Comment by taoeffect** [comment]
Can you expand on what is meant by "communication primitives"? Is this at all related to the sort of thinking in #284?

**Comment by cmontella** [comment]
By communication primitives we mean making communication an explicit and fundamental operation in the language, as much as "join" or "union". And by communication, we mean it in the literal sense like "send an email to everyone in this table" or "send yourself a text message when a Facebook friend who doesn't live in your city is currently in your city"
