### ISSUE TITLE
Please make port configurable.

### ISSUE THREAD

**Issue by berndca** [witheve/Eve#226]
Eve run on port 8080. This is a rather popular port. Please provide an option to run eve on a different port. This could be configured in a file or perhaps a command line parameter could be added to run.sh.

It would also be helpful to have the option to just start the Eve server instead of launching the default browser (would fix #203). My default browser is firefox which complains about the script index.js to hang at line 146 when I try to create a query. I have not been able to open the editor in chrome. This issue appears to be related to websockets.

**Comment by joshuafcole** [comment]
Yeah we need to add a port flag and update the webserver to pull the port from an environment variable. The option to start without launching the editor already exists as the `--restart` flag, but that may not be the most obvious name for it.

**Comment by cmontella** [comment]
You can also start the server alone by just running the server binary. In the runtime directory, run:

`cargo run --bin server --release`

**Comment by berndca** [comment]
I ran 
    cd runtime
    cargo run --bin server --release

It compiles and the last few lines output read
         Running `target/release/server`
    Warning, cannot migrate state for: "d602bc17-f092-4afd-8909-bacf2e6f2597"
    Warning, cannot migrate state for: "4f8d2632-6395-4f94-b2b6-2aa0567fcf97"
    Warning, cannot migrate state for: "4f8d2632-6395-4f94-b2b6-2aa0567fcf97"
    Warning, cannot migrate state for: "4f8d2632-6395-4f94-b2b6-2aa0567fcf97"
    Warning, cannot migrate state for: "4f8d2632-6395-4f94-b2b6-2aa0567fcf97"
    Warning, cannot migrate state for: "92afc227-7144-48ca-8e6c-00f5e0fdf345"
    Warning, cannot migrate state for: "372043ef-09fe-4189-88cc-22c504bb89ad"
    Warning, cannot migrate state for: "372043ef-09fe-4189-88cc-22c504bb89ad"
    reading saved state took 0.5880601200042292s

However I do not seem to be able to connect. Both browsers I tried (Chrome and Firefox on Linux - Elementary Freya 64 bit) show an empty page and seem to be busy executing a script until the browser offers to kill the unresponsive script.

**Comment by cmontella** [comment]
I've added the ability to specify port for the static file server... As for your issue, we've seen this in the past, and it was a bug in rust's websocket library relating to the number of connections. Can you tell us what script it's hanging on? In Chrome, just open the dev panel and go to Network, it should tell you which script hasn't loaded. Thanks!

**Comment by berndca** [comment]
All scripts seem to load. The request which hangs is for root ('\', localhost:2794, plain, 0B). 14 javascript files have been loaded before successfully.

The browser seems to get stuck at indexer.ts, line 132. 

There is also a console message "slow parse (> 5 ms)" caused by client.ts:150

**Comment by joshuafcole** [comment]
Try deleting the autosave file located in runtime/autosave

On Wed, Aug 19, 2015 at 4:53 PM, Bernd Meyer <notifications@github.com>
wrote:

> All scripts seem to load. The request which hangs is for root ('\',
> localhost:2794, plain, 0B). 14 javascript files have been loaded before
> successfully.
>
> The browser seems to get stuck at indexer.ts, line 132.
>
> There is also a console message "slow parse (> 5 ms)" caused by
> client.ts:150
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/witheve/Eve/issues/226#issuecomment-132828791>.
>



-- 
Screw the environment. Please print this email immediately. And then burn
it.

**Comment by berndca** [comment]
Thanks, the site is loading. The data previously entered, when I worked through the tutorial is gone. This is probably expected.
