### ISSUE TITLE
Unable to get packages from source

### ISSUE THREAD

**Issue by ricburton** [witheve/Eve#227]
I *think* I’ve installed all the necessary things. Am I doing something wrong here?

```
Richards-MBP-2:eve richardburton$ bash run.sh --verbose
* Checking dependencies...
~/dropbox/dev/eve ~/dropbox/dev/eve
* Compiling Editor...
~/dropbox/dev/eve
* Opening /Users/richardburton/dropbox/dev/eve/ui/waiting-room.html
~/dropbox/dev/eve ~/dropbox/dev/eve
* Updating rust if necessary...
multirust: using existing install for 'nightly-2015-08-10'
multirust: override toolchain for '/Users/richardburton/dropbox/dev/eve/runtime' set to 'nightly-2015-08-10'
* Compiling server... (This takes a while)
 Downloading rand v0.3.8
Unable to get packages from source
```

**Comment by joshuafcole** [comment]
I think you've installed the necessary things too. This seems like cargo (rust's dependency manager) is having trouble pulling down dependencies for you. It looks like the "Unable to get packages from source" error may have been truncated, but try checking out this cargo issue to see if it can help.

https://github.com/rust-lang/cargo/issues/1258

**Comment by joshuafcole** [comment]
If the issue persists or you still can't figure it out, feel free to comment and I'll reopen this issue and see what I can do to help.
