### ISSUE TITLE
Move save directory out of runtime into eve/saves

### ISSUE THREAD

**Issue by joshuafcole** [witheve/Eve#229]

**Comment by cmontella** [comment]
I added a command line option to save it wherever you want. What's the reason for a saves directory?

**Comment by joshuafcole** [comment]
Common naming convention mostly. Seems like a good default. Did you have
alternative suggestions?

On Wed, Aug 19, 2015 at 6:11 PM, Corey Montella <notifications@github.com>
wrote:

> I added a command line option to save it wherever you want. What's the
> reason for a saves directory?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/witheve/Eve/issues/229#issuecomment-132842608>.
>



-- 
Screw the environment. Please print this email immediately. And then burn
it.

**Comment by cmontella** [comment]
I thought about it more, and this leads to a larger discussion about what an Eve file actually is. For now, yeah let's put everything relative to Saves.

But in a larger sense we need to eventually talk about what "Saving" and "Loading" mean in a system like Eve.
