### ISSUE TITLE
We need to distinguish between different value types

### ISSUE THREAD

**Issue by jamii** [witheve/Eve#231]
The UI so far presents the illusion that everything is just text and numbers can magically be added together. But the internal representation affects semantics through joining, sorting, grouping etc eg "19" will not join against 19.

Either we store *everything* as text and coerce only inside arithmetic, or the user needs to be able to see the difference. This affects display, data entry and importing.

**Comment by cmontella** [comment]
Can we do as Excel does and choose the type on input? If it looks like a number, it's a number. We can handle the corner cases like zip codes, phone numbers, and SSNs specifically (mostly numbers that can start with a zero).
