### ISSUE TITLE
Uncaught TypeError: a.localeCompare is not a function

### ISSUE THREAD

**Issue by rschroll** [witheve/Eve#232]
I've managed to come up with a query that throws this error in the browser when you try to open it.  The result of the "Save to Gist" operation is here: https://gist.github.com/anonymous/80693804489f303327da

The problem is from line 89 of tableEditor.ts, where the comparison function falls back on the localeCompare method.  I've added some debugging and have found that in this case, a is `false`.

It would be easy enough to add a test here for the case of booleans, but I'm not sure how you'd like them to sort.  I also don't know if these booleans are unexpected, which might be a sign of an underlying bug.

This is seen running Eve dd3df3c7 on Ubuntu 14.04 and Chrome 44.0.

**Comment by joshuafcole** [comment]
It's a bit odd, but I think the right solution is to coerce any non-numbers to string to get consistent sorting behavior, so in the default clauses when sorting rows we'd want a.toString().localeCompare(b)
