### ISSUE TITLE
Is it possible to provide a Ubuntu virtual box image to get people to try out Eve?

### ISSUE THREAD

**Issue by zubairq** [witheve/Eve#235]
This would give developers not familiar with Rust or Typescript an easy way to try Eve

**Comment by cmontella** [comment]
I agree, we need an easier way for people to try Eve. Bundling together a binary might be all we need to do though. Any reason for a virtual box image in particular?

**Comment by zubairq** [comment]
Virtual Box comes from Oracle so lands the highest chance of being installed in Enterprises, which mostly buy Oracle products anyway. It doesn't matter that Virtual Box is free, people in Enterprises just care who the vendor is as that gives them a sense of "trust". You have to remember that in most European companies they limit the applications that can be installed on your desktop. If you want a new application, Virtual Box in this case you have to go through a several weeks process if it all goes quickly

**Comment by joshuafcole** [comment]
While I agree that we'll need to make the process of using Eve simpler for industry when it's ready, this is meant primarily to be a tech preview / request for comment. I think I can safely speak for all of us when I ask that nobody use Eve in production yet without the implicit guarantee that it will eat your laundry and report your dog as a threat to national security.

When we are ready though, we're planning to provided a hosted in-browser service so people in enterprise don't need to download anything at all.

**Comment by zubairq** [comment]
That sounds brilliant if there will be a hosted version or one click installer. Actually for Enterprises even to use thing in development we usually need to go through the approval process. I did it here in a 5000 person company for LightTable and it took quite a long time, even though only 2 people used it. 

So I look forward to a download first I assume and then later a hosted version in the future! :)
