### ISSUE TITLE
Interface bug in Safari 8.0.8

### ISSUE THREAD

**Issue by salmazov** [witheve/Eve#260]
<img width="1019" alt="screen shot 2015-09-08 at 11 24 58" src="https://cloud.githubusercontent.com/assets/1635615/9730011/5737b94a-561c-11e5-896d-b99c85726e9d.png">

**Comment by cmontella** [comment]
Yikes! Thanks for the bug report. We haven't really done testing in browsers other than Chrome and Firefox, so this is definitely expected. We will definitely test more browsers as our development becomes stabilized.

**Comment by ibdknox** [comment]
We'll track making safari work in #262.
