### ISSUE TITLE
Interface bug in Chrome - horizontal scroll/move?

### ISSUE THREAD

**Issue by salmazov** [witheve/Eve#261]
How can I regroup my items on the query screen? I can't access to main entity. 

<img width="1111" alt="screen shot 2015-09-08 at 11 27 05" src="https://cloud.githubusercontent.com/assets/1635615/9730077/9fda36a0-561c-11e5-8917-aa38d165991c.png">

**Comment by cmontella** [comment]
Hm, I can definitely see how that's a problem. We probably need a feature to reset the layout in the case something like this happens, although we are presently exploring new interface ideas.

Out of curiosity, how did you arrive at this state? Were the nodes place this way for you, or were you moving a node and were able to drag it off screen?

**Comment by 3demax** [comment]
I'm also affected by this bug, and was able to reproduse it. 
This happens to me when I'm trying to click and drag some node while the search window is open and some other node is selected. The latter reacts to this action as if it happens to on, but with a huge offset. [As demonstrated in this video](https://github.com/witheve/Eve/files/72282/eve_bug_cursor.mkv.zip)
