### ISSUE TITLE
Installation fails with `Eve requires tsc version "1.6.0-dev.20150731" but "" is installed`

### ISSUE THREAD

**Issue by mydoghasworms** [witheve/Eve#268]
I am trying to install Eve on Mint/Ubuntu.

After installing Multirust successfully using the script, I try running `run.sh`, but it fails as follows:

```
bash run.sh
* Installing commit hooks...done.
* Checking dependencies...npm WARN package.json eve@0.0.0 No README data
npm http GET https://registry.npmjs.org/codemirror
npm http GET https://registry.npmjs.org/typescript/1.6.0-dev.20150731
npm http 200 https://registry.npmjs.org/typescript/1.6.0-dev.20150731
npm http GET https://registry.npmjs.org/typescript/-/typescript-1.6.0-dev.20150731.tgz
npm http 200 https://registry.npmjs.org/codemirror
npm http GET https://registry.npmjs.org/codemirror/-/codemirror-5.6.0.tgz
npm http 200 https://registry.npmjs.org/typescript/-/typescript-1.6.0-dev.20150731.tgz
npm http 200 https://registry.npmjs.org/codemirror/-/codemirror-5.6.0.tgz
run.sh: line 71: =0: command not found
run.sh: line 73: return: codemirror@5.6.0: numeric argument required
/usr/bin/env: node: No such file or directory

  x Eve requires tsc version "1.6.0-dev.20150731" but "" is installed. Please reinstall using:
    cd ui && npm install && cd .. before continuing.
```

Trying the advice on the last line simply gives:

```
npm WARN package.json eve@0.0.0 No README data
```

and after that, there is no improvement.

I am not sure if this is due to me having interrupted the installation previously. I did delete `~/.npm` and started again, but things are not OK.

**Comment by mydoghasworms** [comment]
OK, I found the issue. The `tsc` binary is present, but expects the binary `node` to be installed on the system. I am using the `nodejs` package from the standard repositories, which provides a binary called `nodejs`. By simply creating a link from node -> nodejs, I got past the problem.

**Comment by cmontella** [comment]
Glad you got it working! I'm going to post a link here to a discussion in the mailing list about this exact topic, so anyone encountering this issue in the future can get more info: https://groups.google.com/forum/#!topic/eve-talk/5zqL7soVLGo

We will make the install process more streamlined so this isn't a problem in future releases.
