### ISSUE TITLE
Can't run Eve, in a broken state

### ISSUE THREAD

**Issue by simonhughes22** [witheve/Eve#281]
``` bash
~/GitHub/Eve> sh run.sh 
* Installing commit hooks...done.
* Checking dependencies...done.
* Compiling editor...done.
* Opening editor: /Users/simon.hughes/GitHub/Eve/ui/waiting-room.html
* Rust is up to date.
* Compiling and running server. This takes a while...
     Running `target/release/server`
Warning, cannot migrate state for: "82d487ac-dda8-43b5-b140-b28de6e30055"
Warning, cannot migrate state for: "82d487ac-dda8-43b5-b140-b28de6e30055"
Warning, cannot migrate state for: "82d487ac-dda8-43b5-b140-b28de6e30055"
Warning, cannot migrate state for: "82d487ac-dda8-43b5-b140-b28de6e30055"
Warning, cannot migrate state for: "82d487ac-dda8-43b5-b140-b28de6e30055"
Warning, cannot migrate state for: "7d20d1cb-3834-4ac6-a3dd-c4bd8cc434b1"
Warning, cannot migrate state for: "499d5aea-5c88-4626-b851-2a8623c1bd7a"
reading saved state took 0.49511173903010786s
```

It now refuses to run. This was after running through the tutorial and importing the CSV file, which I think I did twice as the back button did not refresh the home page to show the new card. How do I reset Eve so that it works?

**Comment by simonhughes22** [comment]
Deleted the autosave in the ./saves folder.

**Comment by joshuafcole** [comment]
Thanks for posting your solution. This is one of the issues with iterating the editor quickly. The latest editor progress is currently located in the ui/experiments folder. It can be accessed by going to "/madlib" on the page the server opens. We need to add a warning to the editor when it detects an out of date autosave file to prevent this in the future.

**Comment by simonhughes22** [comment]
I had a couple of other issues. Going back didn’t always refresh (I had to force it) so for instance after importing a file I didn’t see it by hitting back without forcing a refresh.

While it works now (although it hung the first time),  I get a bunch of errors in the console (See screenshot) on the initial wait page before it redirects correctly.

I am running it on Mac OS X Yosemite.

This looks like an interesting tool. To be honest, it reminds me a lot of Ms Access right now (not necessarily a bad thing), but I see a lot of potential once you add in more features and editors.

Simon

From: Joshua Cole
Reply-To: witheve/Eve
Date: Saturday, October 3, 2015 at 2:06 PM
To: witheve/Eve
Cc: Simon Hughes
Subject: Re: [Eve] Can't run Eve, in a broken state (#281)


Thanks for posting your solution. This is one of the issues with iterating the editor quickly. The latest editor progress is currently located in the ui/experiments folder. It can be accessed by going to "/madlib" on the page the server opens. We need to add a warning to the editor when it detects an out of date autosave file to prevent this in the future.

—
Reply to this email directly or view it on GitHub<https://github.com/witheve/Eve/issues/281#issuecomment-145279331>.
---------------------------------------------------------------------------------------
 This email has been scanned for email related threats and delivered safely by Mimecast.
 For more information please visit http://www.mimecast.com
---------------------------------------------------------------------------------------

**Comment by joshuafcole** [comment]
When going back, were you using the browser's back button or the back command in the left bar? The latter should always work, but we didn't get around to implementing pushState for the former. It doesn't look like the picture has come through, but if the errors are along the lines of `Warning, cannot migrate state for` those are just diagnostic output rather than issues. Eve Stores the full history of it's database (your autosave file) rather than just the current state. When the server restarts, it replays that history to reach where you left off. Those messages arise when a field is added to a table and are harmless. (For the nitty gritty as to why they crop up, it's because when a field is added, the runtime does not know what default value to fill the column with for existing entries. Therefore, it nukes the table. The editor then sends up a diff containing all of the previous entries with a sane default value provided for the new  field. From the user's side, this is seamless).

Cheers

**Comment by simonhughes22** [comment]
I was using the Eve back button not the browsers. The console errors I get on the wait screen are:

Uncaught ReferenceError: drawn is not defined
client.ts:121WebSocket connection to 'ws://localhost:2794/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

Thanks,

Simon

From: Joshua Cole
Reply-To: witheve/Eve
Date: Saturday, October 3, 2015 at 4:16 PM
To: witheve/Eve
Cc: Simon Hughes
Subject: Re: [Eve] Can't run Eve, in a broken state (#281)


When going back, were you using the browser's back button or the back command in the left bar? The latter should always work, but we didn't get around to implementing pushState for the former. It doesn't look like the picture has come through, but if the errors are along the lines of Warning, cannot migrate state for those are just diagnostic output rather than issues. Eve Stores the full history of it's database (your autosave file) rather than just the current state. When the server restarts, it replays that history to reach where you left off. Those messages arise when a field is added to a table and are harmless. (For the nitty gritty as to why they crop up, it's because when a field is added, the runtime does not know what default value to fill the column with for existing entries. Therefore, it nukes the table. The editor then sends up a diff containing all of the previous entries with a sane default value provided for the new field. From the user's sid e, this is seamless).

Cheers

—
Reply to this email directly or view it on GitHub<https://github.com/witheve/Eve/issues/281#issuecomment-145291503>.
---------------------------------------------------------------------------------------
 This email has been scanned for email related threats and delivered safely by Mimecast.
 For more information please visit http://www.mimecast.com
---------------------------------------------------------------------------------------
