### ISSUE TITLE
Why choose rust?

### ISSUE THREAD

**Issue by MrMormon** [witheve/Eve#282]

**Comment by joshuafcole** [comment]
Performance. We considered clojurescript, but couldn't bear the performance hit in something as performance sensitive as a join algorithm or a constraint solver. We previously implemented the runtime in vanilla javascript, but that wasn't fast enough either. We're hoping once the rust -> emscripten buildchain is more stable that it will provide a suitably fast in-browser solution.

**Comment by MrMormon** [comment]
What other languages did you consider?
