### ISSUE TITLE
Eve should use AI

### ISSUE THREAD

**Issue by taoeffect** [witheve/Eve#284]
> **Janeway:** "Computer, run a subspatial harmonic frequency analysis on the gravimetric distortions and check for any anomalies."

I'm not joking. I've been programming since I was 12. Know C, C++, Objective-C, Java(Script), Clojure, Scheme, newLISP, etc. etc. etc.

I feel we are still in the programming stone age. Programming is cumbersome. Time consuming. And ridiculously error prone.

We can do better, and Eve is about doing better. I love what you guys are doing, but I think AI has a big role to play in the future of programming. 

Check out, for example, what huge difference Apple's Interface Builder made for programming, and especially when they added smart constraints. And that's "dumb AI", not even an AI so much as an algorithm.

We need the machine to start inferring more based on more compact and abstract instructions.

Can you imagine trying to run if you had to run the way we program computers? Manually giving your muscles nerves every single specific instruction on how to fire and when? You'd never make it a foot.

**Comment by cmontella** [comment]
Thanks for your thoughts! Yeah, AI has a great potential to change the way we do all sorts of things, including programming. But it's still a very nascent science and hard to apply in a general way. As you note, there are so many things we can do with a programming language to make it better which are lower hanging fruit than general AI. So, while we're always looking for new approaches, AI is one of the area we aren't specifically targeting in the near future.
