### ISSUE TITLE
Advanced queries tutorial - editor hangs

### ISSUE THREAD

**Issue by beyonix** [witheve/Eve#285]
I have been following the tutorial (with pleasure!) but encountered a number of hangs throughout the process that I haven't been able to reproduce in a consistent manner.

When I say I haven't been able to reproduce it consistently, I mean that I can't minimise a set of actions that always result in this behaviour. I have however been able consistently to make the process hang by just starting a new query, adding a few sources and doing arbitrary actions on them (within the possibilities offered by the GUI). The failure manifests itself at the moment that I click on a source or attribute of the source (never on an action of the sidebar), and more specifically, I believe only when I switch selection between sources (not just between attributes of one source, but less certain of this). Between the decisive action and the initial creation of the query lie for me between 2 and 20 seemingly arbitrary actions... However, all my cases included multiple instances of the same source in a query (could not reproduce without). But the hangup happened both when switching sources of the same type, and sources of different type.

To be more precise on the 'hanging': The browser process (Chrome 46.0.2490.71) will fully use one cpu core for the tab in which the page was loaded and become unresponsive. Closing and reopening the page seems to help most of the time, though occasionally, I have had to restart Eve entirely. Lastly, I observe a "Send error on event: WebSocketError: I/O failure" in the terminal that launched Eve (using run.sh), when the hang occurs.

Sorry for the loads of random observations, but I figured, better provide all the information I have then to leave something out that was crucial for you guys. If you want me to try anything in particular to attempt to reproduce it, just give me a poke :)

**Comment by cmontella** [comment]
Thanks for the observations, these issues can be difficult things to debug. We've had reports of hangs before, and I want to make sure the following situation isn't happening to you: When you bring in multiple sources in the query editor, Eve automatically attempts to product join them. In the tutorial, we ask you to bring in a source with 150 rows. Some uses accidentally bring in that source three times, meaning a product join result of literally millions of rows, which our runtime can't handle at this point. So this is one cause of a hang we've seen in the past. It doesn't quite sound like that's happening to you, but I wanted to point you in that direction in case it was.

Can you verify whether or not this is your situation?
