### ISSUE TITLE
Query Graph Editor: Modifier key for dragging a node and all connected nodes

### ISSUE THREAD

**Issue by jakedowns** [witheve/Eve#290]
I realize a user can drag out a selection box to select multiple nodes, and that one can also use the SHIFT key.

But, when adding query primitives I find myself wishing there were a quick modifier key I could use when dragging them that would automatically move their connected nodes at the same time. Perhaps alt, cmd/ctrl, or even holding down shift.

Any interest in this? If so, I'd be willing to dig into it.

**Comment by ibdknox** [comment]
If we were sticking with that UI, it's something we'd definitely be interested in (and were planning to do ourselves), but we've switched gears with the interface to something that should be far more useable. 

And the new stuff will be coming in the next few weeks :)
