### ISSUE TITLE
madlib spacing

### ISSUE THREAD

**Issue by markrhacker** [witheve/Eve#291]
![screen shot 2015-11-04 at 21 15 25](https://cloud.githubusercontent.com/assets/13749803/10952196/6e34b680-8339-11e5-9d68-73995a3da69a.png)

Madlib spacing is not working..
Thanks

**Comment by cmontella** [comment]
Yeah, that doesn't look right. Could you provide a little more information for us to help diagnose the problem? e.g. what OS version and browser version are you running here. What are the steps to reproducing this result? Anything you can add would be helpful. Thanks!

**Comment by ibdknox** [comment]
I think a recent version of chrome changed the way flexbox renders. I have a suspicion this is a victim of that.

**Comment by markrhacker** [comment]
Sorry, new to all this.
MacOs El Capitan 10.11.1
Chorme Version 46.0.2490.80 (64-bit)
Lastest pull from Git

Loving Eve! Keep up the inspiring work

**Comment by markrhacker** [comment]
Could be.... I'll leave it to the experts :)
I'm Aerospace Engineering by trade - (very) amateur programmer - therefore Eve is just the sort of tool I've been looking for.
Thanks
