### ISSUE TITLE
Tomcat server blocks Eve installation

### ISSUE THREAD

**Issue by tdoughty1** [witheve/Eve#295]
I attempted to install Eve on a computer with a Tomcat server.  After installing rust with the included script, I ran run.sh and got the following output:

    * Installing commit hooks...done.
    * Checking dependencies...done.
    * Compiling editor...done.
    * Opening editor: /home/tdoughty1/Packages/Eve/ui/waiting-room.html
    * Rust is up to date.
    * Compiling and running server. This takes a while...
         Running `target/release/server`
    thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Error { repr: Os { code:      98, message: "Address already in use" } })', ../src/libcore/result.rs:736

I believe this is because Tomcat is already using the 8080 port.  According to a [previous issue](https://github.com/witheve/Eve/issues/259), the port can be configured differently.  Where does this configuration occur?  And can the run.sh file be modified to account for this?

Thanks for your help. This looks like a great tool.

**Comment by cmontella** [comment]
The sever address is specified as a flag when the server is started. e.g. from the runtime folder
```
cargo run --bin server --release -- -f 0.0.0.0:8081
```
will run the server at localhost on port 8081.

Now, if you want to configure the run script to do this automatically, you can set this flag in the variable rustFlags on line 151. e.g.

```
rustFlags="--release -- -f 0.0.0.0:8081"
```

The only problem here is the automatic browser redirect still points to localhost:8080, so it will show a page now found error. So you'll also have to go into ui/waiting-room.html and change the port on line 45 to the one you specified in the run script.

I know this seems a little complicated, but we're promising to make the build and configuration process nicer in the next release. In the meantime, let me know if you encounter any other troubles.

**Comment by tdoughty1** [comment]
Worked great, thanks for your help!
