### ISSUE TITLE
404 after Waiting Room

### ISSUE THREAD

**Issue by dylanjt3** [witheve/Eve#296]
I'm getting a 404 after Eve compiles from `bash auto.sh`. All dependencies are installed and compilation succeeds - it seems like, as far the console is concerned, everything is running smoothly.

But my browser goes from your waiting-room.html to localhost:8080/editor, with a 404 not found in the body.

**Comment by cmontella** [comment]
Can you post the console output on the run script? Also, can you confirm nothing else is running on port 8080 and 2794?

**Comment by dylanjt3** [comment]
Console output:

    * Installing commit hooks...done.
    * Checking dependencies...done.
    * Compiling editor...done.
    * Opening editor: /Users/dylan/projects/Eve/ui/waiting-room.html
    * Rust is up to date. 
    * Compiling and running server. This takes a while...
         Running `target/release/server`
    reading saved state took 0.00009282497921958566s

Nothing else is running on either of those ports. I've tried reinstalling dependencies, etc. If this doesn't make much sense on your end then of course I am entirely open to the possibility that it is a local issue on my machine.

**Comment by cmontella** [comment]
One more question: is it serving a default 404 page, or the Eve 404 page? i.e. ui/404.html

**Comment by dylanjt3** [comment]
@cmontella nevermind. I have a daemon running on port 8080. Disabled service and all works well. Sorry about this!

**Comment by cmontella** [comment]
Thanks okay, no problem. FYI, you can configure the port Eve uses so that you can keep your process running on 8080. See this thread: https://github.com/witheve/Eve/issues/295

Let us know if you need anymore help, and of course any comments or suggestions you have.
