### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by cmontella** [witheve/Eve#326]

**Comment by Mouvedia** [comment]
http://early.witheve.com/tutorials/intro%20tutorial/tutorial.html
from http://www.chris-granger.com/ leads to a 404

**Comment by Mouvedia** [comment]
@cmontella the link in the blog post is still leading to a 404: why are you closing this issue?

**Comment by cmontella** [comment]
Mouvedia,

I did a bulk issue close because they're all moot at this point. The linked tutorial is for a version from last year, and it's gone from the main repo. But it exists in history if you want to see it here

https://github.com/witheve/Eve/tree/82ff0cfbf22ab5008d648de5fe6efa812b591e05/tutorials/intro%20tutorial

**Comment by Mouvedia** [comment]
Then edit the blog post with that one.

**Comment by cmontella** [comment]
Mouvedia,

The core issue is that the tutorial was hosted on GitHub pages, which only points to the latest master. Since the tutorial is out of date, it's not on the latest master. I've asked Chris to link to the tutorial in the repository, but we won't be hosting it.

Corey
