### ISSUE TITLE
SSLv3_method error in Debian

### ISSUE THREAD

**Issue by zonca** [witheve/Eve#334]
I have compilation errors under Debian testing.

I am trying to build the current master of Eve.
I install multirust fine, but then building Eve gets:

    multirust/toolchains/nightly-2015-09-17/cargo/registry/src/github.com-0a35038f75765ae4/openssl-0.6.5/src/ssl/mod.rs:151: undefined reference to `SSLv3_method'

I followed the steps here: https://github.com/sfackler/rust-openssl/issues/305
and managed to build Eve.

**Comment by cmontella** [comment]
Zonca,

Thanks for the tip. We only tested building on Ubuntu, and even there we had plenty of problems with rust relating to OpenSSL. Going forward we will be sure to test on more platforms to avoid errors such as this.

Thanks again!
