### ISSUE TITLE
how do I play with the latest eve?

### ISSUE THREAD

**Issue by ccorcos** [witheve/Eve#336]
At the end of [this talk](https://www.youtube.com/watch?v=VZQoAKJPbh8), you show a new Eve. Is that in this repo? Can I play with it? 

Also FYI, I think [antimony](https://vimeo.com/125111378) has a really interesting interface for programming. Its actually kind of just a visualization of LISP.

Anyways I really like what you guys are building here. I'd love to help!

**Comment by vprimachenko** [comment]
check out `experimental\cardwiki` and run

    npm install
    npm run dev

**Comment by 100ideas** [comment]
Is it necessary to run `./run.sh` anymore to set things up?

**Comment by ibdknox** [comment]
It shouldn't be. :)
