### ISSUE TITLE
Unremovable broken image in a card

### ISSUE THREAD

**Issue by shamrin** [witheve/Eve#344]
Manually adding broken url into `add` cell with multiple images permanently puts broken image in the card. With no way to remove it. Demonstration:

![untitled](https://cloud.githubusercontent.com/assets/510678/13324162/8c4f262a-dbed-11e5-97a1-731a708484f9.gif)

**Comment by cmontella** [comment]
Yes, this is definitely a bug. At this point though, we are moving away from this interface, so we won't be fixing it.
