### ISSUE TITLE
Imags

### ISSUE THREAD

**Issue by markrhacker** [witheve/Eve#345]
Image File:// URL not working

eg
'''file:///Users/markhacker/Eve/0ba7c39.jpg'''

MacOS
Chrome
Git Pull 27 Feb

**Comment by joshuafcole** [comment]
Hey @markrhacker,
Due to web security policies, it's impossible to access resources on file:// urls from a website that is hosted on a server (even if that server is localhost!). You'll need to host those images separately for Eve to be able to work with them.
