### ISSUE TITLE
Please create a wiki with some Getting Started docs

### ISSUE THREAD

**Issue by kristianmandrup** [witheve/Eve#347]
When I start Eve, all I get is a container of existing cards. How do I create new cards etc. Please add some documentation on the wiki. Thanks :)

**Comment by joshuafcole** [comment]
Hey @kristianmandrup this is on the todo list! We made the conscious decision not to ship with a tutorial to learn more about what UX users might find confusing in the wild, but we'll be adding a tutorial before doing a true public release.
