### ISSUE TITLE
AUTOGENERATED_home_THIS_SHOULDN'T_SHOW_UP_ANYWHERE in url when searching "home"

### ISSUE THREAD

**Issue by makoConstruct** [witheve/Eve#349]
steps to reproduce: Search "home"

The error occurred when the DB is fresh. I doubt any of the articles I added contributed to the issue.
OS: Debian Linux
Browser: Chrome 46

**Comment by cmontella** [comment]
Thanks, contrary to what it says, this behavior is expected and fine.
