### ISSUE TITLE
npm run dev fails to start the application.

### ISSUE THREAD

**Issue by michalczaplinski** [witheve/Eve#363]
On node `4.3.2` & npm `2.14.12`
OS: Linux Mint

`npm run dev` results in the following output and no application launched.

![eve](https://cloud.githubusercontent.com/assets/5417266/15179408/c64ed216-177b-11e6-9d31-431e741be8ce.png)

**Comment by bosskopp** [comment]
Same behavior on Ubuntu 15.10, nodejs v5.11.1, npm 3.8.6.
`npm install` thows just one warning:

> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm  WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12

`nodejs run.js -w -v` returns:
![bildschirmfoto vom 2016-05-11 17-58-01](https://cloud.githubusercontent.com/assets/1733427/15187613/04a96d8e-17a2-11e6-9b4a-86ddec05e793.png)

**Comment by jonmacro** [comment]
Same behavior on OSX 10.11.4, nodejs v4.2.2, npm v3.8.3.

The result of running `npm run dev` in iTerm2 v2.9:

![screen shot 2016-05-13 at 11 34 46 am](https://cloud.githubusercontent.com/assets/16058457/15237093/830d3d20-18fd-11e6-9c0a-615c18cbc45f.png)

**Comment by cmpis** [comment]
Still the same.

### Versions

```
cp at Chriss-MacBook-Pro in ~/src/Eve (master)
$ node -v && npm -v && uname -a
v6.1.0
3.8.6
Darwin Chriss-MacBook-Pro.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
```

**Comment by lewisjb** [comment]
After some debugging the problem is uncaught exceptions, specifically:
`Error: ENOENT: no such file or directory, realpath '<Eve>/src/wiki.ts` (and also `/test/NLQPTest.ts` and `/test/runtimeTest.ts`). Which seem like valid errors as those files don't exist.

If you remove/comment out lines 17, 20, and 21 it won't give those errors; however nothing happens that I can see.

**Comment by ibdknox** [comment]
I just fixed this, the following should get this version up and running:

```
npm install
npm run dev
cd server/
lein run
```

Open `localhost:8081/repl` and login with chris/chris

**Comment by michalczaplinski** [comment]
Hi Chris, that appears to run the application successfully on my end, although the original `npm run dev` still  seems to fail:
```shell
[czaplinm:~/Testing/Eve] master ± npm run dev

> eve@0.0.0 dev /home/czaplinm/Testing/Eve
> node run.js -b repl

KILLING PROCS
[czaplinm:~/Testing/Eve] master 3s
```
