### ISSUE TITLE
Random segv after period of inactivity

### ISSUE THREAD

**Issue by joshuafcole** [witheve/Eve#365]

**Comment by convolvatron** [comment]
unable to reproduce after large scale changes. will leave this open, please add comments for any segvs you see, and if at all possible platform information and a stack trace. thanks

**Comment by shamrin** [comment]
@convolvatron By the way, what are the necessary preparations for a possible future segv? I don't want to lose stack traces / core dumps in case it happens.

**Comment by convolvatron** [comment]
in bash on mac and linux you can enable coredumps using 'ulimit -c'

if you happen to get one on the mac:
   it will be placed in the /cores directory as /cores/core.<pid>
   you can open it using 'lldb <exectuable> -c <core file>'
   and 'bt' will give you the stack trace

on linux:
    core should be in the current working directory
   you can open it using 'gdb <exectuable> <core file>'
   and 'bt' will give you a stack trace

if you run 'lldb eve' (or 'gdb eve' on linux), then type 'run <arguments>' a segv will
stop the process and allow you to backtrace and examine its state.

but unless you have a repo, the core thing is probably the best approach for things
that happen rarely and you dont have a reproduction for. we're bringing up a
test harness (in eve!) to do correctness and stress testing, so hopefully we can  
wring things out a bit more so external developers/users wont have to deal with
alot of systemic/background bugs
