### ISSUE TITLE
Timers try to account for missed ticks

### ISSUE THREAD

**Issue by ibdknox** [witheve/Eve#369]
Our default timer implementation should probably just snap to the latest tick instead of trying to make up ticks as it gets behind. An example of the symptom this causes can be seen in https://github.com/witheve/lueve/issues/3.

**Comment by convolvatron** [comment]
we need to add a timer which doesn't try hard to emit the correct number of events, for this application it should skip events that are further in the past than the clock period

**Comment by ibdknox** [comment]
Timers can also saturate the the server such that it doesn't ever send messages to the client.

**Comment by cmontella** [comment]
Fixed with 0.2
