### ISSUE TITLE
Subaggregates store excessive state to handle crossing

### ISSUE THREAD

**Issue by joshuafcole** [witheve/Eve#382]
Due to our cardinality semantics, aggregates can't necessarily be shuffled to the end of a pipeline and must therefore be capable of restoring cardinality.

Two obvious ways of accomplishing this are:
- Capture all inputs to `subagg` and cross the aggregate result out in the tail
  - This means storing all intermediates flowing through `subagg` until flush
- Reorganize the DG such that aggregates come as early as possible, and duplicate any preceding scans after the aggregate
  - This repeats the computation rather than storing the registers
  - Preferably the scans will be re-adorned such that variables in the `subagg` grouping will be bound, but for an MVP post-filtering of the existing scans should work
  - In the situation where two aggregates need to be crossed at different cardinalities, everything gets sad.

In an effort to get things working as quickly as possible, we've decided to do the first approach, but this requires more thought since it's a huge bottleneck compared to the rest of evaluation.

**Comment by convolvatron** [comment]
ideally at the minimum if there were no cross we wouldn't need to hold the state, with the temporary approach we do. i guess the next intermediate step would be to detect the cross and signal the builder. this would actually allow an incremental and conservative cutting of pre and post aggregate evaluations on a per-case basis without any runtime changes

**Comment by convolvatron** [comment]
i think this is no longer the case in the new GJ runtime? i haven't been able to find the cross at least we should try to remember to visit this during review

**Comment by ibdknox** [comment]
Yeah, we only store the state necessary to project the values/groups for the aggregate, no other state is stored.
