### ISSUE TITLE
error attempting to == different types

### ISSUE THREAD

**Issue by convolvatron** [witheve/Eve#386]
seems like in that particular case, silently returning false is the right approach

**Comment by joshuafcole** [comment]
Agreed, do you want to change it or shall I?

Unfortunately, that means breaking != out from the macro, since it has the opposite cross-type comparison result (true)

**Comment by joshuafcole** [comment]
Fixed in https://github.com/witheve/Eve/commit/1d7565fb0e67c48df7bc5c953676ec87747d4006
