### ISSUE TITLE
Superfluous #num in examples/logic.eve?

### ISSUE THREAD

**Issue by dram** [witheve/Eve#395]
Is `#num` in  [examples/logic.eve#L4](https://github.com/witheve/Eve/blob/master/examples/logic.eve#L4) redundant:

```
 [#div #num text: "If you see this, it's an error."]
```

**Comment by ibdknox** [comment]
It's not used in that example, but there's nothing wrong with it. It helps make that div more specific as now you could find all the divs generated by that with a rule like so:

```
Find num divs
  div = [#div #num]
```

It'll be a pretty common pattern to have combinations of tags and names as a way to classify different objects in the system.

**Comment by dram** [comment]
OK, I'll close this issue.
