### ISSUE TITLE
Right and left click

### ISSUE THREAD

**Issue by dram** [witheve/Eve#396]
Can Eve distinguish right-click from left-click? It seems that [#click] will be triggered by both of them.

**Comment by joshuafcole** [comment]
We should either add a `button` attribute to `#click`s or split these into
`#right-click` and `#left-click`. The first is more flexible (e.g.,
supporting middle click, MB4, MB5, etc., so I recommend that one.

**Comment by dram** [comment]
I also prefer this one: `[#click button: ...]`.

**Comment by ibdknox** [comment]
FWIW, that would be a departure from the standard dom event, which sends `contextmenu` in the case of a right click. Not saying I feel strongly about it, but it's something we should be aware of.

**Comment by joshuafcole** [comment]
I don't think this is a huge problem, but I'm open to hearing alternative arguments.

**Comment by joshuafcole** [comment]
I've gone ahead and provisionally added support  for this using a `button` attribute on the click  event. This should transparently keep working for existing clicks, with the exception that right clicks will count as well. In our example cases so far, this is not an issue. Going forward, clicks can be filtered using the button attribute.

**Comment by joshuafcole** [comment]
If this proves to be an issue for users, we can always back out of the change.

**Comment by joshuafcole** [comment]
Actually, thinking about this more, this really isn't going to work until we have an event model that can synchronously respond to the browser. As is, we'd need to always cancel default on right click or you'd never be able to prevent the context menu. I'm going to back out of this and re-open the issue.

**Comment by cmontella** [comment]
Fixed in https://github.com/witheve/Eve/pull/823
