### ISSUE TITLE
Escape double quote inside string

### ISSUE THREAD

**Issue by dram** [witheve/Eve#401]
Currently following code seems to be broken, is escaping double quote inside string supported?

```
match
  foo = "foo\"bar"
bind
  [#pre text: foo]
```

**Comment by ibdknox** [comment]
Weirdly enough this is actually a bug in our JSON parser. We're hoping to land a much better JSON parser today that I've confirmed fixes this. Will close once that hits master.

**Comment by ibdknox** [comment]
New parser is in! :)
