### ISSUE TITLE
Bring back indented code blocks?

### ISSUE THREAD

**Issue by dram** [witheve/Eve#404]
I found that CommonMark support both "Fenced code blocks“ and "Indented code blocks"[2]. Indented code blocks is similar to Eve's previous mechanism for block delimitation, except that four spaces are required.

Personally, I prefer indented code blocks, which looks cleaner and need less characters to type. I wish indented code block support in Eve can be bring back.

[1] http://spec.commonmark.org/0.26/#fenced-code-blocks
[2] http://spec.commonmark.org/0.26/#indented-code-blocks

**Comment by cmontella** [comment]
Dram,

We're currently reevaluating how we want to support markdown. I'll keep this issue open, so anyone who agrees with you can voice their support. When we have a better idea about the markdown story, we'll post an update here and probably on the mailing list.

**Comment by cmontella** [comment]
I think this issue can be closed, we won't be going the indent route, but code blocks are created easily in the editor with the ctrl+k shortcut.
