### ISSUE TITLE
Using bind operator : outside of object causes server to crash

### ISSUE THREAD

**Issue by cmontella** [witheve/Eve#414]
Repro:

Some stuff

```
match
  [#session-connect]
  board-size: 3
commit
  [@board board-size ]
```

Changing the line to `board-size = 3` will not crash the server.

**Comment by joshuafcole** [comment]
Turns out this is my error for expressions with no schema at all.

**Comment by joshuafcole** [comment]
For this particular issue, since we've been telling people that `=` and `:` are interchangeable, I'll just have support for both. We can discuss whether we want that separately if necessary, and rigging this implosion up to the errors system will be tracked in a separate issue.
