### ISSUE TITLE
make commit ids stable

### ISSUE THREAD

**Issue by convolvatron** [witheve/Eve#417]
we discussed eliminating the distinction between maintain and commit id stability, 
in order to reduce the fixed point issues and make the semantics more consistent.

this allow allows the implementation to optionally use a hash of supports for an id
instead of persisting them

additionally we discussed making a hard distinction between the attributes used 
at the time of entity generation "foo = [#bar z @joeoy]" as being explicit supports,
and additional attributes bound later as not

we should do those things or discuss why we shouldn't be doing them

**Comment by ibdknox** [comment]
> additionally we discussed making a hard distinction between the attributes used 
at the time of entity generation "foo = [#bar z @joeoy]" as being explicit supports,
and additional attributes bound later as not

That one is already the case, so we're good there.

**Comment by ibdknox** [comment]
Fixed in https://github.com/witheve/Eve/commit/3856a144ab368ba9cbdda5f7f258f7c1da2d4a1b
