### ISSUE TITLE
Segmentation fault after page refreshing

### ISSUE THREAD

**Issue by dram** [witheve/Eve#420]
Eve exit with a segmentation fault error after I refresh page, following is the output:

```
% build/eve

----------------------------------------------

Eve started. Running at http://localhost:8080


fixedpoint in 0.000036 seconds, 0 blocks, [ 2 ] iterations, 0 changes to global, 1 maintains, 0.000013 seconds handler
fixedpoint in 0.000014 seconds, 0 blocks, [ 1 ] iterations, 0 changes to global, 0 maintains, 0.000012 seconds handler
fixedpoint in 0.000054 seconds, 0 blocks, [ 2 ] iterations, 0 changes to global, 3 maintains, 0.000020 seconds handler
Segmentation fault
```

**Comment by cmontella** [comment]
Dram, can you pull latest and confirm this behavior is still happening? There was an issue we identified and fixed this morning PST that might be related to this.

**Comment by cmontella** [comment]
I'm pretty sure this is fixed by https://github.com/witheve/Eve/commit/0ad36a86371967d053a392cda2d1f27a8124a11a

So I'm going to close this. If you are still having an issue, I'll reopen it and we can investigate more.
