### ISSUE TITLE
Use of not() in conditional breaks cardinality

### ISSUE THREAD

**Issue by bertrandrustle** [witheve/Eve#426]
Run the following:

    Create objects
    ```
    bind
      [@a]
      [@b]
    ```
    
    Bind the binding of one object contingent on presence of `#foo`
    ```
    match
      a = [@a]
      b = [@b]
    
      // Broken:
      foo = if not(a = [#foo]) then a else b
    
      // Working:
      // foo = if a = [#foo] then b else a
    bind
      [#div text: "foo.name is {{foo.name}}"]
    ```

Expected output:

    foo.name is a

Observed output:

    foo.name is b
    foo.name is a

Next, comment out the line indicated as being broken and uncomment the line indicated as being working, then compile and run again. The observed output is as expected:

    foo.name is a

So it appears the `not()` expression is breaking expected behavior.

**Comment by joshuafcole** [comment]
Okay, the parse and compilation of this guy looks fine, which indicates that we've likely stepped into an executor edge case.

**Comment by joshuafcole** [comment]
More concerningly, the `concat` node is only getting hit with a cardinality of one, which might mean that we're dealing with a retraction bug. @convolvatron might want to take a peek

**Comment by cmontella** [comment]
fixed on ts-merge
