### ISSUE TITLE
not does not pass cardinality dependencies, resulting in misorderings

### ISSUE THREAD

**Issue by convolvatron** [witheve/Eve#428]
no such file!
```
   match
      [#http-request]
      [#path index:f token]
      not([#path index:count[given: f] file])
   commit
      [#http-response
       status:"404"
       reason:"No such object"]
```

---------------------------------------------------------
 Unknown generated variable
 (passed string)

 Generated variable "|f|" was never provided in query

 31|      [#path index:f token]
                      ^

 This is almost certainly an implementation issue. Please send your full query and this error to Eve's maintainers for assistance.

**Comment by joshuafcole** [comment]
The root cause here was child DG's creating their own identical cardinal terms. Since the terms were separate tables, they did not show as equivalent, so were never linked as a dependency.
