### ISSUE TITLE
Implement "none" for removing objects and attributes

### ISSUE THREAD

**Issue by ibdknox** [witheve/Eve#431]
The parser now accepts `none` as a special value for removing an entity or removing AVs in a set or merge. For example (committed as `examples/not-working/erase.eve`): 

```
  commit
    [#f foo: "yo"]
    [#g @cool]
```

remove stuff
```
  match
    f = [#f]
    g = [#g]
  commit
    f.foo := none
    g := none
```

@joshuafcole we need compiler support for the `g := none` case, which currently blows up with:

```
../src/compiler.lua:1136: Eliding only binding on object: mutate<erase>{binding{ENTITY -> variable<g>}, }
stack traceback:
	[C]: in function 'error'
	../src/compiler.lua:1136: in function 'unpackObjects'
	../src/compiler.lua:1245: in function <../src/compiler.lua:1219>
```

@convolvatron the builder has two new cases here: a mutate whose operator is `"erase"` and a constant whose constantType is `"none"`. The erase mutate operator removes all AV pairs for the given E. The `none` constant shows up only in set mutates and only as a value. If `do_set` sees a `none` as the value, it would do the normal erase logic, but not add a new value.  As an alternative to this second case, we could potentially take another step in the compiler to turn this into a special op instead of having none as a constant type, but this seemed reasonable. Totally up to you.

**Comment by ibdknox** [comment]
The parser work is on the `modularity` branch.

**Comment by ibdknox** [comment]
As an aside, we can plumb this a different way if we want, the above suggestions just seemed like the smallest set of changes that get the behavior.

**Comment by cmontella** [comment]
fixed on ts-merge
