### ISSUE TITLE
Included program causes fixedpoint time to slowly climb rendering eve unresponsive (query without tag at fault?)

### ISSUE THREAD

**Issue by frankier** [witheve/Eve#437]
So I was trying to port an asteroids-like game from a Haskell example to get to grips with Eve (and help test it). I'm abandoning it for now due to this issue. Therefore please excuse that this bug probably isn't quite the minimum possible steps to reproduce but rather a before and after. See the two commits in this gist for the change: https://gist.github.com/frankier/bb00f2c4cd3d3435b84c0cf5bfd2be2a/revisions

Before:
Eve leaks about 4MB/sec but fixedpoint time is fairly stable

After:
Eve still leaks about the same but fixedpoint time climbs rapidly

Before the change typical console output:
fixedpoint in 0.001462 seconds, 21 blocks, [ 2 2 ] iterations, 30 changes to global, 30 maintains, 0.000687 seconds handler

A couple of minutes later it's climbed to:
fixedpoint in 0.045364 seconds, 21 blocks, [ 2 2 ] iterations, 30 changes to global, 35 maintains, 0.001162 seconds handler

and eve is unresponsive.

**Comment by cmontella** [comment]
Frankier,

Can you confirm if this is still happening in 0.2?

**Comment by cmontella** [comment]
Frankier, I'm going to go ahead and close this, because I don't think this should be happening with the new runtime.
