### ISSUE TITLE
Can crash parser with fairly small program

### ISSUE THREAD

**Issue by frankier** [witheve/Eve#438]
See below:

    ```
    bind
      [a: ""{{}}"]

Output from master branch is:
```
...
lua error
../src/error.lua:65: The parser has wandered off somewhere horribly wrong. There's a STRING_CLOSE token where stackTop is a object node instead of a concat node
stack traceback:
	[C]: in function 'error'
	../src/error.lua:65: in function 'string_close'
	../src/parser.lua:728: in function 'parse'
	../src/parser.lua:1813: in function 'parseString'
	../src/compiler.lua:1188: in function <../src/compiler.lua:1187>
[1]    4231 segmentation fault (core dumped)  eve syntaxerror.eve
```

**Comment by cmontella** [comment]
fixed on ts-merge
