### ISSUE TITLE
Commit global causes segmentation fault/core dump

### ISSUE THREAD

**Issue by frankier** [witheve/Eve#447]
Steps to reproduce:
1. Run eve [connections.eve](https://github.com/witheve/Eve/files/458370/connections.txt).
2. Open your in browser in one tab.
3. Open again in another tab.

Result:
segmentation fault (core dumped)

Expected result:
Anything else ;)

**Comment by cmontella** [comment]
Playing around with it, it seems like commit global is killing it. This program provides a minimal repro:

```
commit global
  [foo: "foo"]
```

**Comment by ibdknox** [comment]
Are you by chance using the docker container?

**Comment by frankier** [comment]
I wasn't. This running the binary produced by following the compilation instructions on Ubuntu 16.04.1 LTS.

**Comment by cmontella** [comment]
Not relevant in 0.2
