### ISSUE TITLE
If record is changed in two ways during the same event, searches for both values match

### ISSUE THREAD

**Issue by alltom** [witheve/Eve#467]
# Race

Clicking the "Race" button triggers two search blocks, both of which set `foo.name`. As a result, both values of `foo.name` are displayed on the page. This implies that `:=` creates a copy of the record on its left, which seems to be a bug?

Clicking the "Don't race" button triggers only one search block, which sets `foo.name` to a third value. As a result, the old values of `foo.name` disappear and only the new one is shown. This implies that `:=` mutates the record on its left, as documented.
## Code

Create a foo.

```
commit @global
  [#foo]
```

Display the foo's value.

```
search @global
  [#foo name]
bind @browser
  [#div text: "foo.name: {{name}}"]
```
### Give `foo.name` two values during one button click

Create a button to click on.

```
commit @browser
  [#button text: "Race", name: "start"]
```

When the button is clicked, set `foo.name` to `"first"` _and_ `"second"`.

```
search @event @global @browser
  [#click element: [name: "start"]]
  foo = [#foo]
commit @global
  foo.name := "first"
```

```
search @event @global @browser
  [#click element: [name: "start"]]
  foo = [#foo]
commit @global
  foo.name := "second"
```
### Give `foo.name` one value during a button click

Create a button to click on.

```
commit @browser
  [#button text: "Don't race", name: "start2"]
```

When the button is clicked, set `foo.name` to `"third"`.

```
search @event @global @browser
  [#click element: [name: "start2"]]
  foo = [#foo]
commit @global
  foo.name := "third"
```

**Comment by ibdknox** [comment]
Sorry for the insanely delayed response! 

This might seem a bit odd, but this isn't a bug, it's a product of our semantics. The set operator `:=` is equivalent to removing all the current values of that attribute and asserting the new value in the next time step. In this case, two blocks are running at the same time, so they both remove the current values and then each assert a value. As a result, when we get to the next time there are two values. The reason it works this way is that blocks are unordered and therefore we need some way of thinking about how changes merge. Our current semantics are based on sets, so if two things are proposed there are now two values in the set. You could imagine other semantics, but they seem more arbitrary and they let potential issues hide under the surface. For example if we tried to deterministically choose one to overwrite the other, it's easy for something like code position or id or some such to change and fundamentally change the result of your program.

If you happen to have thoughts on how we could make this better, we'd certainly be open to hearing them!

**Comment by alltom** [comment]
I see. It does seem oddly complicated at first. To predict the result, I'd have had to guess that `:=` happens in two phases, and guess what the phases were. My experience with assignment in other languages is probably hurting me here. To me, `:=` implies *replacing* the data in a cell, not *adding* it.

I'll get used to it. :)
