### ISSUE TITLE
Minor typo in Syntax Reference PDF

### ISSUE THREAD

**Issue by JoeArizona** [witheve/Eve#469]
Page 1, in Record section: "The predominate data structure in Eve is a record."

Should be predominant. See: https://www.vocabulary.com/articles/chooseyourwords/predominate-predominant/

**Comment by cmontella** [comment]
Thanks for spotting this. Fixed here: https://github.com/witheve/assets/commit/0d80064a2b699a83c2b4e954fa552534b1eb0182
