### ISSUE TITLE
No error message

### ISSUE THREAD

**Issue by Machiaweliczny** [witheve/Eve#472]
![image](https://cloud.githubusercontent.com/assets/5442370/19814911/9f2ef9f4-9d40-11e6-8c87-79fd9b5337e9.png)
When working with tutorial and modifying record attribute its simply doesn't bind anything to '#div' from example without showing any error. Why is it so? How can this be fixed?

**Comment by Machiaweliczny** [comment]
Ok i get it. It simply doesn't find the record. Maybe it would be nice to highlight which code is beeing executed based on if search matched something or not.

**Comment by joshuafcole** [comment]
Hey Damian!

The UX is a little rough right now (it's a work in progress), but if you
use the inspector tool on a block and ask "Did this fail?" It'll actually
do just that!
