### ISSUE TITLE
Docs: npm install must be run in /scripts folder

### ISSUE THREAD

**Issue by garthgoldwater** [witheve/Eve#473]
I'm on Mac OS 10.11.6 running node with nvm.

#### The docs say:

> You'll need a recent [node.js](https://nodejs.org) and then:

>  
> ```
> npm install
> npm start
> ```

#### But running `npm install` without first `cd`ing into the `scripts` directory results in the following error:

```
module.js:474
    throw err;
    ^

Error: Cannot find module '[omitted]/eve/Eve/install'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3

```

This isn't friendly to people who don't already work with node regularly.

I can submit a pull request to README.md if y'all think this is important.

**Comment by joshuafcole** [comment]
Hey @garthgoldwater,

This is very strange. Running npm install from within the scripts folder actually shouldn't work at all. I'd expect (given the way it's written) for it to only work if you're in the root `eve` directory. Can you please provide a little more information about your working directory?

If you could make a new clone to get a fresh state and paste logs of the following, I'd really appreciate it.

From the directory you were unable to install in:
```
$ ls
$ pwd
$ npm i
$ ls
```

From the scripts folder:
```
$ ls
$ pwd
$ npm i
$ ls
```

Hope we can get to the bottom of this soon!

**Comment by garthgoldwater** [comment]
OK, I think this is my bad -- I did a fresh clone and couldn't reproduce the original bug. 

However, if I remove the original Eve folder and then clone again, I **can** run `npm install` in the `scripts` folder. 

I suspect this is happening because I have an `eve` directory inside my general coding related directories, which then has an `Eve` folder _inside it_ when I clone the repo in (I wasn't sure about file structure, so I assumed I'd save various `.eve` files in the outer folder as I play around with the IDE). IE:
```
Eve master ✔ pwd
/Users/garth/code/freaksworld/eve/Eve
```

For the logs: Do you want me to do a fresh reinstall between the two instances of `npm i`, since it is now successfully installing from the `Eve` directory? (not an npm expert here)

**Comment by joshuafcole** [comment]
You should be good to go. After thinking about it I realized that npm will
walk the folder hierarchy upwards til it finds a package.json (In eve's
root folder) and then execute the command there. That explains why it would
work in a subdirectory, and if you were perhaps in a parent directory of
the project when you first ran it that would explain the initial failure to
install.

Thanks for getting back to me so quickly! If anything else comes up, please
let us know.

**Comment by garthgoldwater** [comment]
I did happen to run `ls` immediately after the bug happened (the one time it did happen):
```
Eve master ✔ node install
module.js:474
    throw err;
    ^

Error: Cannot find module '/Users/garth/code/freaksworld/eve/Eve/install'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3
Eve master ✔ ls
ATTRIBUTIONS.md	README.md	examples	   scripts		tsconfig.json
LICENSE		csrc		index.html	src		typings
Procfile	css		package.json	test

```

**Comment by joshuafcole** [comment]
Oh! I see, that repo was checked out to the last version of eve, which had
a different build  process. That's why the fresh clone fixed the problem.

Cheers

On Fri, Oct 28, 2016, 11:59 garthgoldwater <notifications@github.com> wrote:

I did happen to run ls immediately after the bug happened (the one time it
did happen):

Eve master ✔ node install
module.js:474
    throw err;
    ^

Error: Cannot find module '/Users/garth/code/freaksworld/eve/Eve/install'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3
Eve master ✔ ls
ATTRIBUTIONS.md README.md   examples       scripts      tsconfig.json
LICENSE     csrc        index.html  src     typings
Procfile    css     package.json    test


—
You are receiving this because you modified the open/close state.


Reply to this email directly, view it on GitHub
<https://github.com/witheve/Eve/issues/473#issuecomment-257001447>, or mute
the thread

**Comment by garthgoldwater** [comment]
Here's a question: I made the directory and cloned the repo at 1PM today. Why would the old version be there?

**Comment by garthgoldwater** [comment]
wait: the problem was that I was writing `node install` and not `npm install`. I'm an idiot, sorry.

**Comment by joshuafcole** [comment]
Not a problem, typos happen!
