### ISSUE TITLE
Point witheve.com at programming.witheve.com

### ISSUE THREAD

**Issue by tbodt** [witheve/Eve#474]
The site at programming.witheve.com is, I think, a much better landing page for people who don't know anything about Eve. witheve.com seems to me like it was written before Eve ever existed, and it doesn't really have any useful links. Not even a link to programming.witheve.com.

**Comment by r0br0dz** [comment]
Hacker News is using your suggestion. I just arrived myself. Never made
software and this is interesting

**Comment by joshuafcole** [comment]
Done and done! Thanks for the tip.
