### ISSUE TITLE
Scrolling in the new editor doesn't work in Firefox

### ISSUE THREAD

**Issue by heyLu** [witheve/Eve#475]
I have had a quick look into the console and the code, but found no errors and obvious things.  Does this work for other people?  (:+1: if this happens for you as well.)

**Comment by r0br0dz** [comment]
Firefox does not scroll for me either. Going to use Chrome

**Comment by deepj** [comment]
Yup, the same problem here.

**Comment by joshuafcole** [comment]
Thanks for pointing this out!  I was lax doing a final test of FF yesterday night and had broken it due to some flex styling. :( Should be all good now! If anything else crops up (after making sure to clear cache!) please let me know and I'll deal with it ASAP.
