### ISSUE TITLE
README Quick Start Tutorial Link broken

### ISSUE THREAD

**Issue by NEWeber** [witheve/Eve#476]
In the root `README.md`, the link for the Quick Start Tutorial (http://docs.witheve.com/guides/quickstart/) is broken.

The same link also exists in http://docs.witheve.com/ and is also broken.

**Comment by cmontella** [comment]
Thanks, fixed!

**Comment by NEWeber** [comment]
Readme looks good! FYI, the link on  http://docs.witheve.com/ still points to the old broken link.
