### ISSUE TITLE
Make an Eve 0.20 release

### ISSUE THREAD

**Issue by RubenSandwich** [witheve/Eve#477]
First off congratulations on launching 0.20!

I can't wait to sink my teeth into it and try to break it with all of my limited mental might.

One thing however that would be helpful is to release a 0.20 version. I can see why you wouldn't release a new release. A big reason would be because you plan on getting everyone to build from source because you plan on iterating quickly. But I still think it's worth doing because with the new announcement people will come here looking for 0.20 and be confused when they don't see it in 'release'.

**Comment by cmontella** [comment]
Done: https://github.com/witheve/Eve/releases/tag/0.2
