### ISSUE TITLE
Decoding `null` in JSON throws an error

### ISSUE THREAD

**Issue by xymostech** [witheve/Eve#478]
When trying to decode JSON that has a `null` value in it from a `[#request]` in `@http`, I'm seeing a JavaScript exception being thrown [here in eavs.ts](https://github.com/witheve/Eve/blob/master/src/runtime/util/eavs.ts#L29).

A solution would be to just check for `null` right before that line. I don't know if there's a way to represent `null` in Eve though; if not then maybe it makes sense to leave off that value from the constructed record? Or maybe there should be an explicit `null` value to represent this case, so that `toJs(fromJs(json)) == json`?

**Comment by boneskull** [comment]
fwiw `typeof null === 'object'"

**Comment by joshuafcole** [comment]
While we dont plan to support null as a first class value in eve, we intend
to add a  "#json-null" record or similar to the @http bag to maintain
idempotence  when reserializing.
