### ISSUE TITLE
Double inequality should be `min < variable < max`

### ISSUE THREAD

**Issue by csiz** [witheve/Eve#480]
I just found out about the project so I'm basing this on the documentation page http://docs.witheve.com/handbook/inequality/.

This looks pretty weird  `value <= variable >= value` . Python and every math class I've been in did it like `min <= var <= max`.

**Comment by olejorgenb** [comment]
Yeah, this threw me off too.

You can sort of look at it like the < > illustrates a region.

    ------->.......<--------
           2       5          
    .......<------->........
    
    --- inside the region
    .... outside region

`2 > live-neighbours < 3 ` means  `live-neighbours < 2 or 3 < live-neighbours`

If one should express this using the `min<val<max` the best I can come up with is `3 < live-neighbours < 2` which looks a bit odd, and have a implicit 'or' instead of 'and' in the `min < val < max` case.

I think it could grew on me, but not convinced it's a good idea yet.

**Comment by csiz** [comment]
If you rent to emphasise readability then throwing users off is a bad idea. My gripe is that `<` now has 2 meanings in the same context. One is the ubiquitous thing on pointy bit is smaller than thing on wide bit, the other is inside outside. But there's not even a context change like C++ streams for example `out << name`.

Secondly I think the case of inside, ie. `min < var < max` is so but more common than outside that it's not worth having syntactic sugar for both. `var < under or over < var` is short enough as it is. If you end up using it enough in one project you can make a function of it.. `outside[value: users, under: 3, over: 5]`.

Your suggestion is definitely confusing as well.

**Comment by olejorgenb** [comment]
Off topic: I don't see any explicit `and` either? `x > 2 and x < 100` in a search block results in `Nothing is providing a value for and`

**Comment by cmontella** [comment]
This is fixed by https://github.com/witheve/docs/commit/2eced0b7d195a461b5fa36ffd97706b4861f8d0a

**Comment by cmontella** [comment]
`min < var < max` implicitly means that `min < var` and `var < max`

We could write the same thing in two lines:

```
min < var
var < max
```

This will filter var to only those that satisfy both conditions.

If you want a block to run under certain conditions, you can use an `if` expression. This following block will run if `foo` is A or B.

```
search 
[foo]
display = if foo = "A" then "output"
                else if foo = "B" then "output"

bind @view
  [#value | value: display]
```
