### ISSUE TITLE
Eve install failed

### ISSUE THREAD

**Issue by HolocronLabs** [witheve/Eve#481]
Hi,

Unfortunately, when I try to install Eve on Ubuntu 14, I get this error. Any suggestions would be greatly appreciated as I'm looking forward to trying it out.

![image](https://cloud.githubusercontent.com/assets/13574377/19827310/710ee042-9d5a-11e6-9f5a-e1985effc91a.png)

**Comment by shamrin** [comment]
> `"/usr/bin/node" "/usr/bin/npm" start`
> `v0.10.48`
> `v2.15.1`

Please install a more recent [node.js](https://nodejs.org). I don't know what version is the minium, but for me personally node v4.3.2 works well (OS X).

**Comment by HolocronLabs** [comment]
Appreciate the response. I tried version 4, 5 & 6 of nodejs and still could not get it working. I suspect it might be because I'm using ubuntu 14.04 LTS (server), because I got it working on windows 8 no problem.

**Comment by r0br0dz** [comment]
Run as user not root

**Comment by r0br0dz** [comment]
Actually do git pull and npm install as user then npm start ;)

**Comment by brianwhited** [comment]
1. Install Bash - https://msdn.microsoft.com/en-us/commandline/wsl/install_guide
2. Install Node On Bash - https://aigeec.com/installing-node-js-on-windows-10-bash/
3. Type `exit` to go back to a user prompt from sudo
4. Download Eve - https://github.com/witheve/Eve/archive/master.zip
5. I downloaded Eve to my desktop and extracted it to C:\
6. In Bash, go to the extracted directory by typing `cd mnt/c/Eve-master/Eve-master`
7. Install Eve by typing `npm install`
8. Type `npm start`
9. Open a web browser to http://localhost:8080

**Comment by vickychijwani** [comment]
Are you using [yarn](https://yarnpkg.com/) instead of `npm install`? I got the same error with yarn, so I did `rm -r node_modules`, `npm install`, and `npm start` - that worked.

**Comment by cmontella** [comment]
I'm going to close this issue, because I believe the answer was to install as user, and not root. I encountered this same issue with the making the Docker container and this was indeed the fix.
