### ISSUE TITLE
Reload shortcut?

### ISSUE THREAD

**Issue by eriksvedang** [witheve/Eve#482]
Is there a keyboard shortcut for making the document re-evaluate? A tooltip for this when hovering the reload button would be nice.

(PS. awesome work)

**Comment by ibdknox** [comment]
Yep! `ctrl+enter` will run and `ctrl+shift+enter` will reset (cmd works on mac). 

I agree on the tooltip. We just didn't have time to add some of the finer touches we meant to. Want to open an issue to track adding tooltips? :)

**Comment by eriksvedang** [comment]
I'm on Mac and this reloads the whole page (web browser style), is that the correct behaviour? I was expecting it to only reload the rightmost pane. No big deal if it should be like this, I just want to know if it's a bug.

I can definitely open an issue for tooltip (or give it a shot myself..!)
