### ISSUE TITLE
Extra credit example in Quickstart not working

### ISSUE THREAD

**Issue by DjebbZ** [witheve/Eve#486]
Hi, reporting a bug while following the [Quickstart](http://play.witheve.com/#/examples/quickstart.eve)

Steps to reproduce :
1. Open the Quickstart in a new Incognito browser window (I'm using Chrome 54 on macOS)
2. Jump to Extra Credit with the TOC
3. Enable the two blocks of code
4. Fill the form with some data and click "Submit"

Expected results :

A new record is added to the database and the form fields become empty.

Actual results :

Nothing :(

I tried "debugging" with the following code to see if a new record was added to the database but nothing showed up :

``` eve
search
  [#student name grade school]

bind @browser
  [#div text: "{{name}} {{grade}} {{school}}"]
```

Notes :
1. I'm a complete Eve beginner
2. The rest of the code in the page kept working : I could still change the "Hello, world" text and see it updated after clicking the "Refresh" button.
3. I love what you're doing with Eve. Keep up the good work !

**Comment by gabrielrotbart** [comment]
I'm experiencing the same thing.

I would have loved to debug this, but the guides have no mention of how to add break points.  There's actually no mention of the development environment in the guides at all.

**Comment by ibdknox** [comment]
Sorry about that, if you change the last block to:

```
search @event @browser
  [#click element: [#submit]]
  name = [#name-input]
  grade = [#grade-input]
  school = [#school-input]

commit
  // save the new student
  [#student name: name.value, grade: grade.value, school: school.value]
  // reset the form
  name.value := ""
  grade.value := ""
  school.value := ""
```

you should be good to go.

**Comment by ibdknox** [comment]
The reason it was failing is because the #click and the input records aren't in the default database, they're in the event and browser databases.

**Comment by frankier** [comment]
It still doesn't work totally correctly for me. As it is now, the grade is interpreted as a string. So if I enter:
Name: Billy
Grade: 4
School: Sunnydale

I get:
Billy is 45 years old

I should get:
Billy is 9 years old

To correct it I need to change it to the following:
```
search @event @browser
  [#click element: [#submit]]
  name = [#name-input]
  grade = [#grade-input]
  school = [#school-input]

commit
  // save the new student
  [#student name: name.value, grade: grade.value * 1, school: school.value]
  // reset the form
  name.value := ""
  grade.value := ""
  school.value := ""
```

**Comment by DjebbZ** [comment]
Still no luck at all. Changing the code doesn't do anything : form inputs are still no emptied, and my "poor-man logger" still doesn't print anything. I even emptied completely the browser various caches (local/session storage etc.), still nothing.

I decided to look at the browser console. My inputs are displayed, as well as the click on the submit button.

Maybe it's this error at beginning of the page load that breaks something ? :

`data:application/javascript;base64,dmFyIHVyY2hpblRyYWNrZXI9ZnVuY3Rpb24oKXt9LF9nYXE9e3B1c2g6ZnVuY3Rp…:1 Uncaught SyntaxError: Unexpected token var`

The code : `var urchinTracker=function(){},_gaq={push:function(){try {if(arguments[0][0]=='_link')window.location.href=arguments[0][1]}catch(er){}}},_gat={_createTracker:function(){}, _getTracker:function(){return{__noSuchMethod__:function(){},_link:function(o){if(o)location.href=o;},_linkByPost:function(){return true;},_getLinkerUrl:function(o){return o;},_trackEvent:function(){}}}};cxApi={setCookiePath:function(){},chooseVariation:function(){}}var _gat={_getTrackerByName: function(){_trackEvent: function(){}}};`

The error is located at the last `var` declaration : `var _gat=/* ... */`

I don't know if it's related.

I then tried with Firefox (42). No error in the console, but still nothing happens.

**Comment by DjebbZ** [comment]
Ok strange. It half-worked, in the same Chrome and Firefox sessions I just used to post the comment above.

My "debugger" code displays something below the form, but the inputs are not emptied when I click "Submit".

Note that I don't have the same problem than @frankier above.

**Comment by ibdknox** [comment]
This should fix all the issues:

```
search @browser @event
  [#click element: [#submit]]
  name = [#name-input]
  grade = [#grade-input]
  school = [#school-input]
  grade-number = convert[value: grade.value to: "number"]

commit
  // save the new student
  [#student name: name.value, grade: grade-number, school: school.value]

commit @browser
  // reset the form
  name.value := ""
  grade.value := ""
  school.value := ""
```

Let me know!

**Comment by DjebbZ** [comment]
It works indeed. What's the difference ? I see the commits happen now in 2 different databases, and I can understand that. But why the conversion ? I'd love some explanations.

This debug code works whatever I print in the div :

```
search
  [#student name grade school]
  
bind @browser
  [#div text: "{{name}} {{school}} {{grade}}"]
```

**Comment by cmontella** [comment]
This is now fixed in master

**Comment by cmontella** [comment]
@DjebbZ 

The big difference is that the block clears the value of the input records, which are in the `@browser` database. When we reset the value with a bare `commit`, it places those facts into the session database, while the value in the `@browser` database is left untouched, and so still displayed in the input boxes. This is a bug that we should be able to warn you about (We can see that you're reading and writing into different databases)
