### ISSUE TITLE
Warning/error when using an unbound variable is search block?

### ISSUE THREAD

**Issue by olejorgenb** [witheve/Eve#490]
```
search
    s  = [trail]
    not(a = [trail:0])
```

(Terminology for 's' and 'a'? Variable, symbol, ...?)

Possibly related: #445

**Comment by cmontella** [comment]
I'm sorry this went so long without an answer... I think maybe it's been fixed, since the issue to linked to is fixed. I'm going to close this for now, but if you confirm your issue is still happening we can reopen.
