### ISSUE TITLE
Where is my .eve document in the local version of play.witheve?

### ISSUE THREAD

**Issue by meijeru** [witheve/Eve#492]
I downloaded Eve and installed it, then started it and pointed my browser to `localhost:8080`. I get a local copy of `play.witheve`, including all examples. The examples are visible on my hard-disk in the folder `Eve-master/examples`. If I add a new.eve source file in that folder, it shows up in the examples list. However, any edits I make through (local) playwitheve do NOT show up in that source file. Where is the modified source stored, and how can I edit it outside `play.witheve`?

Note: originally posted in the Google group before I found out that people put similar questions here.

**Comment by olejorgenb** [comment]
Doesn't seem to work atm. When you make a change in the browser it seems to only be persisted to localStorage. To reload the file from disk clear localstorage: (open your web-browser's dev tools and type in the console) `localStorage.clear()`

This should be a high priority bug IMO. Creates a very annoying workflow. (I don't trust the local storage, and the webeditor is somewhat buggy)

**Comment by meijeru** [comment]
The web editor is mostly somewhat primitive, e.g. I can't create a clickable link (url).

**Comment by hryanjones** [comment]
Also, copy-pasting between web editors destroys code blocks and other markup :\.

Not sure if this is the right place to bring this up, but for a locally running version is commit supposed to be stored across refreshes? So, if for example you have a form (like in the QuickStart) to add records, add a few, then refresh the page, is it not expected that the committed values would stick around?

**Comment by jonnor** [comment]
@hryanjones whether records persist across refreshes depends on the database in use. When not specifying the default is `@session`, which only has lifetime of the IDE session. I'd expect more persistent options to be available as tings mature, I see references in the code for things like `@shared` and `@stored` for instance.

**Comment by jonnor** [comment]
In master when using `--server` option, the examples/ folder is read from/written to when editing in the IDE.

**Comment by hryanjones** [comment]
@jonnor Yeah, I think `@stored` sounds like what I'm looking for, but it seems to not be formalized yet. The only special databases I see in [the documentation](http://docs.witheve.com/handbook/databases/#special-databases) are `@session`, `@event`, and `@browser`. I definitely see [`@stored` in the view example ](http://play.witheve.com/#/examples/view.eve), but I tried playing with it to store a value across refreshes and couldn't quite get that to work. I'm excited for when that does, in the meantime I guess Eve will just be good for static, single-use apps, games, etc.

**Comment by cmontella** [comment]
> The web editor is mostly somewhat primitive, e.g. I can't create a clickable link (url).

@meijeru I've made an issue to track this: https://github.com/witheve/Eve/issues/574

> So, if for example you have a form (like in the QuickStart) to add records, add a few, then refresh the page, is it not expected that the committed values would stick around?

@hryanjones  correct, refreshing your browser will reset the state of the application as if you were running it for the first time. This is the same as clicking the "Reset" button at the top of the editor. If you want to refresh your program without resetting its state, click the "Play" button at the top instead.

> Yeah, I think @stored sounds like what I'm looking for, but it seems to not be formalized yet.

Actually, `@stored` is an ad-hoc database that exists only for the purpose of the view.eve program. You can create any databases you want just by committing to them. e.g.

```
commit @foo
  [#foo]
```

```
search @foo
  [#foo]

bind @browser
  [#div text: "Found a foo!"]
```

I need to flesh out the database doc to explain that. Tracking it here: https://github.com/witheve/docs/issues/15

As for the topic of this issue, you can put *.eve files in the "examples" directory, and if you edit them in the editor those changes will be reflected back in the source file. You don't need to run with the --server option to get this either. So I'm going to close this issue.
