### ISSUE TITLE
Enhancement request: shared database

### ISSUE THREAD

**Issue by thSoft** [witheve/Eve#493]
[The Chat example](https://github.com/witheve/Eve/blob/86cdca49c37f94cf42c07da490dc516a7e9508d7/examples/chat.eve) states:

> The @shared DB is synced between all clients on the server, letting them pass messages to one another without explicit requests. Since the current version of Eve is running in local-only mode, this will be a bit of an echo chamber.

It would be great if the shared database was implemented and collaborative software (editors, multiplayer games) could be developed with Eve.

**Comment by olafleur** [comment]
The file you linked to does not seem there anymore.

**Comment by thSoft** [comment]
The example was removed (I think exactly because without shared database support, it does not really make sense). I fixed the link.

**Comment by Nikolasoyye** [comment]
Y

**Comment by cmontella** [comment]
The concept of databases has been removed in Eve v0.3, so I'm closing this issue. Sharing will come with a distributed version of Eve (milestone 2 of our roadmap).
