### ISSUE TITLE
Auto-reload?

### ISSUE THREAD

**Issue by willnwhite** [witheve/Eve#495]
Rather than manual reload.

**Comment by ibdknox** [comment]
In what context are you talking about auto-reload?

**Comment by willnwhite** [comment]
Sorry. On play.witheve.com. Rather than having to press reload here:
![screenshot 2016-11-01 16 35 52](https://cloud.githubusercontent.com/assets/8081877/19897784/55f1c532-a051-11e6-9973-ff845472953d.png)

**Comment by cmontella** [comment]
There are pros and cons to this. On the one hand, it's nice to see changes happening live. On the other hand, this can get in the way when working with a multi-step change, where some of the interim states are unstable e.g. they could cause the UI to disappear. In that case, you want to make changes and then update the interface when you are ready to see the results. After working with these systems for a while, the latter kind of workflow, where you want to deliberately see your changes, seems to be more prevalent. 

That said, maybe this could be an optional feature for people who want it?

**Comment by willnwhite** [comment]
I've changed my mind. I agree with what you say about the poor UX of interim states. Now that the buttons have tooltips, the situation has improved. Tooltips/keyboard shortcuts were the solution to my problem, not auto-reload.
