### ISSUE TITLE
Install failed due to `tsc`

### ISSUE THREAD

**Issue by krmaxwell** [witheve/Eve#502]
I did a `git clone` followed by `npm install` as a user (not root) on Ubuntu 16.04 LTS using the distro-installed version of npm and got the following:

```
$ npm install

> undefined install /home/kmaxwell/src/Eve
> tsc

/usr/bin/env: ‘node’: No such file or directory

npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! undefined install: `tsc`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the undefined install script 'tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kmaxwell/src/Eve/npm-debug.log
```

**Comment by joshuafcole** [comment]
Unfortunately it seems ubuntu still calls the node binary `nodejs`. I have it symlink post-install in my dotfiles and forgot about it. If you symlink `nodejs` to `node` it should just work.

This is a bit of a tough nut because other distros have only `node` instead of `nodejs`, so I'll need to add platform detection into the build scripts, which itself needs to be cross platform compatible. :(

We'll keep this issue open to track that until I figure out a reasonable fix.

**Comment by krmaxwell** [comment]
Thanks, `sudo ln -s /usr/bin/nodejs /usr/bin/node` did the trick!

**Comment by xaxes** [comment]
I have the same problem on Arch Linux (which only has node binary). I even tried `sudo ln -s /usr/bin/node /usr/bin/nodejs`, but it didn't help.
```
$ npm install

> undefined install /home/xaxes/Code/Eve
> tsc

src/renderer.ts(372,44): error TS1005: ':' expected.
src/renderer.ts(378,31): error TS1005: ':' expected.

npm ERR! Linux 4.8.4-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! undefined install: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the undefined install script 'tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xaxes/Code/Eve/npm-debug.log
```

**Comment by khalidx** [comment]
sudo npm install -g typescript fixed it for me

**Comment by joshuafcole** [comment]
We now use a local install of typescript so users don't need to install it manually. Unfortunately we don't have a great solution to the ubuntu node situation short of adding a shell script to warn users. As unpleasant as it is, most node projects expect the binary to be named `node`, so we're not going to rock the boat at this time by trying to fix it. If a user install eve via `sudo npm i -g witheve` the resulting `eve` binary should just work, which is the best compromise I have to offer at the moment.

As ever, if anybody has a better solution to fix this during development time as well, I'd be more than happy to accept a PR.
