### ISSUE TITLE
The parts of the runtime written in Eve should be moved out of /examples/

### ISSUE THREAD

**Issue by frankier** [witheve/Eve#505]
Currently parts of the runtime which are written in Eve are located in /examples/. This really confused me recently when trying to find where changes in `@event` were propagated to `@browser`. I guess ideally they could live in /src/eve/ or similar.

**Comment by olafleur** [comment]
Yeah. I agree with that also.

I guess that the point was to show that (part of) Eve is written in Eve itself (which is really cool btw).

So, we are talking about : 
- analyzer.eve
- editor.eve
- event.eve
- inspector.eve
- view.eve

I guess ?

They should probably be in a `/runtime/` directory, but the user should be allowed to see these files (not only those in `/examples/`) some way ?

**Comment by joshuafcole** [comment]
We'll be moving our self-hosted code into it's own directory some time next
week. Some cleanup work is needed to re-enable multiple workspace
directories. Once that's ready, we'll have a folder for examples, for the
self-hosted code, and for users' projects.

**Comment by joshuafcole** [comment]
Sorry that this has taken so long. I've made this possible in 0.2.2, but the UI still needs some work to re-enable showing multiple workspaces. Once that's done, it should be trivial to separate the two (and have as many other workspaces open as you like).

**Comment by cmontella** [comment]
This is finally completed with the v0.3 runtime.
