### ISSUE TITLE
Make real world app with eve now?

### ISSUE THREAD

**Issue by yuanotes** [witheve/Eve#509]
I haven't found any docs about how to export eve code to make a real world app like html, js, css files.

**Comment by tw88** [comment]
yeah same question here. Im curious about that "deployment" process so to speak. I have severeal small "things" i would need, but having to setup whole enviroments the classic way would be to much overhead.
So having a small eve thing deployed to a webserver would be awesome.

**Comment by atomic-swerve** [comment]
@yuanotes @tw88 Eve is still a development-only toolkit:

> Eve is a set of tools to help us think. Currently, these tools include: a temporal query language, a compiler, and a database.

**Comment by jonnor** [comment]
I'd not recommend Eve for real-world apps yet, but see #544 for some work on creating distributable apps.

**Comment by cmontella** [comment]
I think this question is more along the lines of deployment than about putting Eve to real-world use, is that correct @yuanotes?

In terms of deployment, that's a feature coming in the near term. Speaking in general about using Eve in production though, that's definitely not a good idea... yet :)

**Comment by yuanotes** [comment]
@cmontella I think it would be great to build my next side project with eve......  

And thanks @jonnor, that's what I want now. :)

**Comment by joshuafcole** [comment]
Fixed via #571 

Have fun!***

*Please don't trust us for any projects that require high availability or security yet. We're still in very early alpha!
**If you build anything cool though, let us know! We're always excited to see what the community comes up with. :)
