### ISSUE TITLE
Install fails on macOS Sierra

### ISSUE THREAD

**Issue by Mark92630** [witheve/Eve#512]
With node v6.9.1, npm v3.10.0, and the latest Eve download for Mac, the npm install command yields error messages such as:

Invalid name: "@types/commonmark"

for several different @types (one per install attempt).
[npm-debug.txt](https://github.com/witheve/Eve/files/567980/npm-debug.txt)

**Comment by ibdknox** [comment]
I believe this was actually an issue with NPM, see the related HackerNews thread: https://news.ycombinator.com/item?id=12860806

Can you try again?

**Comment by ibdknox** [comment]
Closing for now, if this is still an issue, please feel free to reopen it.

**Comment by Mark92630** [comment]
I looked at the ycombinator thread, but it is far above my technical depth. I see 38 references to NPM, but have no idea how to decide which one(s) affect me.

Also, I don't know what you mean by "try again." Am I supposed to uninstall anything first? I re-downloaded Eve for Mac, unzipped it into a new sub-directory, and ran npm install again, with a similar error message: "Invalid name: "@types/body-parser".

Mark

**Comment by Mark92630** [comment]
$ npm version
{ npm: '3.10.8',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.9.1',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '5.1.281.84',
  zlib: '1.2.8' }

**Comment by Mark92630** [comment]
It looks to my amateur eye as though npm isn't finding any of this @types "stuff" (see the first nine dependencies):

$ cat package.json
{
  "dependencies": {
    "@types/body-parser": "0.0.33",
    "@types/commonmark": "^0.22.29",
    "@types/express": "^4.0.33",
    "@types/glob": "^5.0.30",
    "@types/mkdirp": "^0.3.29",
    "@types/node": "^6.0.41",
    "@types/request": "0.0.31",
    "@types/tape": "^4.2.28",
    "@types/ws": "0.0.33",
    "body-parser": "^1.15.2",
    "chevrotain": "^0.14.0",
    "commonmark": "^0.26.0",
    "express": "^4.14.0",
    "glob": "^7.1.1",
    "mkdirp": "^0.5.1",
    "request": "^2.75.0",
    "typescript": "^2.0.3",
    "ws": "^1.1.1"
  },
  "devDependencies": {
    "faucet": "0.0.1",
    "tape": "^4.6.0"
  },
  "scripts": {
    "install": "./node_modules/.bin/tsc",
    "postinstall": "node ./build/scripts/build.js",
    "build": "node ./build/scripts/build.js",
    "build-dist": "node ./build/scripts/build-dist.js",
    "start": "node ./build/src/runtime/server.js",
    "server": "node ./build/src/runtime/server.js",
    "test": "node ./build/test/all.js | faucet"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/witheve/Eve.git"
  },
  "license": "Apache-2.0"
}

**Comment by deijmaster** [comment]
having issues... Wouldn't be surprised it's mine... Here's the log on macOS sierra

deijbookpro:Eve-master deijmaster$ npm start

> @ start /Users/deijmaster/Downloads/Eve-master
> node ./build/src/runtime/server.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1376:9)
    at Object.<anonymous> (/Users/deijmaster/Downloads/Eve-master/build/src/runtime/server.js:102:8)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! @ start: `node ./build/src/runtime/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script 'node ./build/src/runtime/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build/src/runtime/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/deijmaster/Downloads/Eve-master/npm-debug.log

**Comment by Mark92630** [comment]
$ npm start

> @ start /Users/markwallace/Downloads/Eve-master
> node ./build/src/runtime/server.js

module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/markwallace/Downloads/Eve-master/build/src/runtime/server.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! @ start: `node ./build/src/runtime/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script 'node ./build/src/runtime/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build/src/runtime/server.js
...

**Comment by Mark92630** [comment]
I got it to run this way:

sudo npm install --unsafe-perm
sudo npm start

**Comment by deijmaster** [comment]
@Mark92630 the node.js & npm install seemed to have went well, but once installed, just can't seem to make it work with eve. Note that you shouldn't need to sudo your way in though...

**Comment by joshuafcole** [comment]
Yeah, please don't give eve superuser permissions at any time. I can make
no guarantees that it won't eat your laundry or send loved ones distasteful
emails. It seems like @deijmaster has a separate installation issue from
the bulk of this thread though.

@deijmaster: you appear to have another program or server running on port
8080. We'll add a port flag back shortly, but until then, if its not a
crucial program you can stop it and start eve normally.

@mark92630: your issue still appears to be that you are unable to install
the type declaration modules so the entire install phase bails. As a
workaround (I dont understand the problem well enough to offer a real
solution yet), we can move those to dev dependencies, since they arent
required unless you plan to hack on the eve runtime.

**Comment by ibdknox** [comment]
@joshuafcole doesn't TSC need these to compile though? Seems like install would still fail because the typescript compiler would bail.

**Comment by joshuafcole** [comment]
Right. We can either ship with bogus global declarations like we originally
did or ship the compiled output.

**Comment by pranaygp** [comment]
@ibdknox that's true. I didn't realise this at first. I think a good solution is to throw the built files into VCS as well which are currently being gitignored.

**Comment by pranaygp** [comment]
@joshuafcole chucked compiled files into git with b8ee648

**Comment by joshuafcole** [comment]
If we're going this route (which seems reasonable), let's do it in a
separate release branch. Alternatively, we could just zip the `dist/`
folder produced by build-dist and ship that (which is what powers
play.witheve.com).

**Comment by pranaygp** [comment]
@joshuafcole I've been working on #525 to fix this. We should be able to change this PR's base to a new release branch instead of master if needed. Let me know if/when you make this new branch.

**Comment by Mark92630** [comment]
@joshuafcole - My only goal at this time is to get acquainted with the Eve way of thinking about writing applications. No desire (or knowledge) to get into the internals.

**Comment by cmontella** [comment]
We've got a new installer for v0.3, so I'm going to close this. If installation is still an issue for you with v0.3, please open a new issue and reference this one.
