### ISSUE TITLE
Affect on search of an else-clause attribute reference 

### ISSUE THREAD

**Issue by btheado** [witheve/Eve#522]
I was thinking that the reference to the attribute item.title below in the else clause would not affect which records match:

```
search
  item = [#item idx]
  title = if not(item.title) then "no title" else item.title
bind @browser
  [#div text: "{{idx}} - {{title}}"]
```

and it would behave the same as the combination of these two blocks

```
search
  [#item idx title]
bind @browser
  [#div text: "{{idx}} - {{title}}"]
```

```
search
  item = [#item idx]
  not(item.title)
bind @browser
  [#div text: "{{idx}} - no title"]
```

And for thes two test cases, I do get the same behavior

```
commit
	[#item idx: 0]
 	[#item idx: 1]
```

Result
```
0 - no title
1 - no title
```

```
commit
	[#item idx: 0 title: "title 0"]
 	[#item idx: 1 title: "title 1"]
```

Result
```
0 - title 0
1 - title 1
```

But for a third case, I get different results.

```
commit
	[#item idx: 0 title: "title 0"]
 	[#item idx: 1]
```

Results for 2 block code:
```
0 - title 0
1 - no title
```

Results for 1 block code:
```
0 - title 0
```

I was hoping the two flavors of code would behave the same, but even if that hope is misplaced, I am at a loss to make sense of  the actual behavior of the if-then-else version.

**Comment by ibdknox** [comment]
Your intuition should have been correct - definitely sounds like a bug. I'll take a look.

**Comment by ibdknox** [comment]
This should be good to go. The strangeness was caused by us not correctly setting `item` as an argument to the if.

**Comment by btheado** [comment]
Confirmed fix. Thanks!
