### ISSUE TITLE
Browser refresh required for changes to appear

### ISSUE THREAD

**Issue by wulftone** [witheve/Eve#527]
When I click "Run" (or type Ctrl+Enter) the preview disappears.  Data appears to be saved but I need to refresh the browser window in order to see changes.

```bash
$ google-chrome --version
Google Chrome 48.0.2564.103 
$ cat /etc/lsb-release 
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=16.06.1
DISTRIB_CODENAME=Daniella
DISTRIB_DESCRIPTION="Manjaro Linux"
```

Cool project!  I'd love to use it.

**Comment by pranaygp** [comment]
@wulftone have you tried using the `Reset` button: `Ctrl/Cmd + Shift + Enter`? Does that solve the problem?

**Comment by wulftone** [comment]
Yes, that works, thank you!  I should have been more experimental.  Why have the two separate options?  What's the point, if I may ask?

**Comment by pranaygp** [comment]
Not entirely sure to be honest. I was looking at the source and it seems as if the play button tries to persist the state of every database except for `@session`, thereby only re-evaluating blocks tht use `@session`, however it overwrites `@browser` too. On the other hand, a reset re-evaulates the entire document. 

Someone with more experience may be able to shed more light on this.

**Comment by joshuafcole** [comment]
@Pranay: Close! The "run" button reruns your new code with the exact same
state you currently have (that is, every fact you've committed is still
just as you left it). The reset button on the other hand throws away your
entire state and starts over from scratch. In the event that you need to
reset your state, or get a new block to evaluate that does an unconditional
commit, then you'd want to use the reset button.

**Comment by alexeypetrushin** [comment]
Had same issue, extremely confusing, I thought it some sort of a bug until googled it and found this tread.
