### ISSUE TITLE
Unary minus

### ISSUE THREAD

**Issue by frankier** [witheve/Eve#533]
The current version of Eve doesn't appear to support unary minus. Neither `-1` nor `- 1` work.

(Workaround: use `0 - 1`.)

**Comment by joshuafcole** [comment]
Hey @frankier: I confirmed that `- 1` doesn't work, but `-1` does work for me. We currently don't allow the `- 1` form due to syntactic ambiguity, although we're open to discussing options there. If you've found a situation where `-1` doesn't work though, that's definitely a bug!

Example working `-1`

```eve
bind @browser
  [tag: "div", text: -1]
```

**Comment by frankier** [comment]
Oops. Poor bug reporting. Yeah negative literals are allowed. Not sure how I didn't realise that. Where I actually had the problem was with trying to take unary minus of an identifier like so:
```
search
  x = 42
  y = -x
commit @browser
  [#div text: "{{y}}"]
```

Expected result: -42
Actual result: Error: Nothing is providing a value for y

**Comment by joshuafcole** [comment]
Oh I see! Yeah, this seems like an issue. `-` is a valid character in identifiers so we're stuck in an ambiguity both ways here. I'll pull @ibdknox in on this to discuss parsing options.

**Comment by frankier** [comment]
Well presumably identifiers can begin with a number, so excluding - from being an initial character could work here too I guess.

**Comment by joshuafcole** [comment]
We've kicked this around for a while and decided that this isn't worth changing at the moment. Unfortunately if we were to invalidate `-` as an initial character it would make it impossible to use namespaced CSS in style objects, e.g., `[#div style: [-webkit-user-select: "none"]]` would cease working. Other solutions have similar sets of drawbacks.

For now we're going to officially recommend continuing to use `0 - x`, even though we know it's suboptimal. As we start to see more eve usage out in the wild we can gauge how obnoxious this is in practice and how destructive the various possible fixes for it might be.
