### ISSUE TITLE
Sort may not work as certain positions in search block

### ISSUE THREAD

**Issue by frankier** [witheve/Eve#538]
Given:
```
commit
  [#birthday age: -2]
  [#birthday age: 3]
  [#birthday age: 60]
  [#birthday age: 64]
```
This works:
```
search
  p = [#birthday age]
  ix = sort[value: age, direction: "up"]
  ix = floor[value: random[seed: 0] * count[given: p]] + 1
commit @browser
  [#div text: "A random person is {{age}} years old"]
```
But this doesn't (floor and sort swapped):
```
search
  p = [#birthday age]
  ix = floor[value: random[seed: 0] * count[given: p]] + 1
  ix = sort[value: age, direction: "up"]
commit @browser
  [#div text: "A random person is {{age}} years old"]
```
Expected output: Same at the previous program, A random person is x years old
Actual output: Nothing

**Comment by ibdknox** [comment]
This is almost assuredly a stratification issue, where the aggregates are ending up in a weird order. I'll take a look.

**Comment by ibdknox** [comment]
I believe this is fixed already. I now see the expected output for both cases. I'm going to close, but if this is still happening please re-open and let us know what you're seeing!

As an aside, if there was a stratification issue lurking in here somewhere, I would expect #657 to fix it.
