### ISSUE TITLE
Numeric functions shouldn't return NaN

### ISSUE THREAD

**Issue by cmontella** [witheve/Eve#539]
A function that would return NaN should instead return no results.

**Comment by Cormac-Williams** [comment]
But the question becomes then, how does Eve allow the detection of out of range function use?

Or equally, how does Eve handle divide by zero? 
At the moment, whatever the result that comes out of Javascript is republished. This I agree is probably an issue.

**Comment by Cormac-Williams** [comment]
I got curious so had a play. This push
https://github.com/Cormac-Williams/Eve/commit/8716ca1beb1b4b8a3baf9b66b049d139179e1628 appears to do what you wish, I essentially emulated what is already present in Logical.ts. Let me know if it works for you and I'll make it a formal pull request. 

This code now would not run

search
  div = 1 / 0
  value = "Works"
bind @view
  [#value value:"{{value}}"]

But this code runs correctly

search
  a = 1
  b = 0
  value = if not( a / b ) then
          "Ooops, divide by zero?" else
          a / b
bind @view
  [#value value:"{{value}}"]

So code written carelessly in terms of a divisor or testing for NaN is more than likely going to filter, but still leaving the possibility open of a more nuanced examination if necessary.

**Comment by joshuafcole** [comment]
This has been in since 0.2.2, thanks again!
