### ISSUE TITLE
Specify Eve program to run at startup

### ISSUE THREAD

**Issue by jonnor** [witheve/Eve#559]
Right now for server-side, one has to start Eve, then go to the browser, and click one of the examples to load the code.

Could be a command-line flag like `--load examples/server.eve`.

This would also enable writing an end2end test around the HTTP server example code.

**Comment by ibdknox** [comment]
#571 will solve this in a different way. It starts an Eve evaluation per http request, so you can do anything you want with it :)

**Comment by 100ideas** [comment]
@jonnor I think #571 resolves your issue? 

this works for me (brings up clock.eve):
```bash
# from eve git root dir
$ cp examples/clock.eve ~/Desktop/
$ npm start ~/Desktop/clock.eve 
```
source https://github.com/witheve/Eve/blob/master/bin/eve.js#L51

**Comment by joshuafcole** [comment]
Yep, this is solved, thanks for bringing it up! :)
