### ISSUE TITLE
Attributes of old record get appended to rather than new record inserted

### ISSUE THREAD

**Issue by btheado** [witheve/Eve#585]
Inserting a record having an attribute with the same value a record used to have causes the attributes in the old record to be appended to instead of a new record inserted.

Initial state:
  [#item id: 1]

After step 1 (add item at index 2):
  [#item id: 1]
  [#item id: 2]

After step 2 (change index 2 to 0):
  [#item id: 1]
  [#item id: 0]

After step 3 (add item at index 2):
  [#item id: 1]
  [#item id: (0,2)]

Expected results after step 3:
  [#item id: 1]
  [#item id: 0]
  [#item id: 2]

### Display item
```
search
  item = [#item id]
bind @browser
  [#div sort: id text: "{{id}} - {{item}}" item]
```

### Test code to reproduce misbehavior
Initialized some test items and add "step" buttons which when clicked in order
will show the behavior
```
commit
  [#item id: 1]
commit @browser
  [#div text: "Click on text in steps 1-3 in order" children:
    [#ol children:
      [#li text: "add item at index 2" #step1]
      [#li text: "change index 2 to index 0" #step2]
      [#li text: "add item at index 2 again" #step3]]]
```

Steps 1 and 3 take the identical action. If they are in separate blocks
then the misbehavior doesn't happen
```
search @event @browser
  id = if      [#click element: [#step1]] then 2
       else if [#click element: [#step3]] then 2
commit
  [#item id]
```

Change the index of item 2 to 0
```
search @event @browser
  [#click element: [#step2]]
search @session
  item = [#item id: 2]
commit
  item.id := 0
```

**Comment by btheado** [comment]
As a workaround I added `[#time frames]` to the search clause and then insert with `[#item frames id]` instead of `[#item id]`. This ensures a new record is inserted rather than an old record appended to.

**Comment by ibdknox** [comment]
If I run the code pasted here, and click the text in order, I get the expected result: 

![image](https://cloud.githubusercontent.com/assets/70036/20536754/29c24d8e-b09f-11e6-9ca1-1cc6fbc46736.png)

Is there something else I need to do?

**Comment by ibdknox** [comment]
oh I see, they're not supposed to both be 39

**Comment by ibdknox** [comment]
The behavior you're seeing here is related to how identity is formed in Eve. The if block creates an item whose identity is made up of `[#item id]`, so if you create two items from this block with the same id, they will have the same identity. As you noted you need something else to make them unique. Instead of frames, I suggest using the click:

```
search @event @browser
  (c, id) = if      c = [#click element: [#step1]] then (c,2)
            else if c = [#click element: [#step3]] then (c,2)
commit
  [#item c id]
```

**Comment by btheado** [comment]
Thanks. Using frames felt less than ideal. Using the click for uniqueness makes much more sense.

**Comment by btheado** [comment]
So one way to put it is changing the attributes which originally contributed to a record's identity, does not change its identity (makes sense).

Instead of changing the identity attributes (i.e. changing the id from 2 to 0 as above), I could have removed the id=2 record entirely and re-inserted it as a new id=0 record. But that would require copying over into the new record fields which had been changed or added on the old record. Using a separate uniqueness attribute is easier.
