### ISSUE TITLE
Crash when searching for all divs in the browser and binding to a view

### ISSUE THREAD

**Issue by nmsmith** [witheve/Eve#591]
See the below code. Note that Eve will not crash if you only search for a _specific_ div you have created. If you count the number of matches with the count aggregate, the search surprisingly returns 3 matches, so that may have something to do with it.

```
commit @browser
  [#div]
```

```
search @browser
  d = [#div]
bind @view
  [#value value: d]
```

**Comment by ibdknox** [comment]
When you say crash, what happens?

This will run infinitely because creating views creates divs which then recurses forever. @joshuafcole maybe we should think about having view go through some other display db?

**Comment by joshuafcole** [comment]
@ibdknox: its actually designed to. Its just being shoehorned through
@browser like @editor is since we dont have configurable db policies yet
and the old client indexing doesn't support multi-dbs. The latter issue is
1-2 full days, to fix. Whats do you think the eta tor the former is?

**Comment by ibdknox** [comment]
> configurable db policies

hm? Do you mean what is sent to the client or not? There's nothing magical about that, we would use a [db impl that sends](https://github.com/witheve/Eve/blob/master/src/runtime/databases/browserSession.ts#L85).

**Comment by nmsmith** [comment]
> When you say crash, what happens?

Eve freezes and you have to kill the process then modify the source file so it doesn't freeze again when you start it back up.
