### ISSUE TITLE
Finding old Eve documents

### ISSUE THREAD

**Issue by atennapel** [witheve/Eve#600]
In a post from Chris Granger from 2015 I saw links like:
https://github.com/witheve/Eve/blob/master/design/language.md
https://github.com/witheve/Eve/blob/master/design/visualProgramming.md
These links no longer work, I was wondering if they still exist somewhere, because I'd love to read them.

**Comment by frankier** [comment]
The old Eve repository has moved to https://github.com/witheve/eve-experiments

See here:
https://github.com/witheve/eve-experiments/blob/master/design/language.md
https://github.com/witheve/eve-experiments/blob/master/design/visualProgramming.md

**Comment by atennapel** [comment]
Thanks!
