### ISSUE TITLE
todomvc: Escape + blur event can give multiple todo bodies

### ISSUE THREAD

**Issue by btheado** [witheve/Eve#607]
Steps to reproduce:

1. Create a todo
2. Double click to edit
3. Make a change to the todo body
4. Hit the escape key
5. The one todo item will now have multiple bodies displayed

I think these two else clauses in the editing block are causing this behavior:

```
   else if [#blur element: [#todo-editor todo value]]
        then (todo, value, false, todo.completed)
   else if [#keydown element: [#todo-editor todo] key: "escape"]
        then (todo, todo.body, false, todo.completed)
```

The escape key is hit and the 2nd clause is triggered and the todo
gets committed with body = todo.body. But then the blur event will
also trigger and this time the todo gets committed with body = value.

I'm not sure what the correct fix is. The blur event can happen in 3
different cases: 1) after enter key is hit 2) after escape key is hit
3) after clicking outside the edit box

For #2 and #3 the edit should be cancelled and for #1 it should be accepted.

Maybe the fix is to update the [#todo-editor value] attribute to match
what was committed into the todo record.

**Comment by shamrin** [comment]
Another problem remains:

1. Double click to edit
2. Make a change to the todo body
3. Hit the escape key
4. Double click again
5. Hit the enter key
5. Get todo doubling again

Demo:

![todomvc](https://cloud.githubusercontent.com/assets/510678/21026603/d2dce636-bda6-11e6-84fa-9a3d9a071ed9.gif)
