### ISSUE TITLE
It is quite difficult to specify a "default only" value for checked and my attempts result in multiple checked values

### ISSUE THREAD

**Issue by frankier** [witheve/Eve#624]
For example, see the settings screen of Minesweeper. Here: https://github.com/frankier/eve-experiments/blob/22dc4b99ea269ee392b1accd58eb5e84c5ceaca2/minesweeper.eve#L436 I maintain a #difficulty-changed record as a flag to see if the user has interacted with the checkboxes. I bind the default value only if not(#difficulty-changed). This is clearly a bit awkward. Perhaps there could be a React like defaultChecked (probably default-checked in our case) attribute.

I guess this is a separate issue, but to run Minesweeper successfully even this doesn't work since I get the error message: Unable to set 'checked' multiple times on entity. It works fine if I just disable the check as I've done here: https://github.com/frankier/Eve/commit/91ff96acdc5a0a24285b2098e6ddf1e223900630

**Comment by frankier** [comment]
I've started working on the first bit of this.

**Comment by joshuafcole** [comment]
hey @frankier,

The current solution to default values in inputs is through binds. It looks like this:

``` eve
search @browser
  value = if [#my-input value] then value
               else "some default"

bind @browser
  [#my-input value]
```

Of course, you can use ifs for defaults anywhere in the stack, not just for DOM. We're keeping an eye on if this proves confusing or unpleasant for users though. If so we'll consider including `defaultValue` attributes ala React.

If you have any other questions or comments about this, feel free to reopen this issue.
