### ISSUE TITLE
Fix opening files on Windows

### ISSUE THREAD

**Issue by cmontella** [witheve/Eve#633]
`Unable to find file 'C:\Users\Corey\Desktop\Eve\examples\clock.eve' in 'root'`

`http://localhost:8080/#/root\clock.eve`

**Comment by cmontella** [comment]
This happens when running a specific eve file with the --editor flag:

```
eve clock.eve --editor
```

**Comment by hammerandtongs** [comment]
I believe this requires #505 to be sorted out?

When opening a specific file with --editor flag it fails if the file isn't in the examples path.

**Comment by cmontella** [comment]
Fixed by: https://github.com/witheve/Eve/pull/651

**Comment by cmontella** [comment]
@hammerandtongs #505 still needs fixing, but this was just an issue of sanitizing slashes.
