### ISSUE TITLE
Handbook/intro Core language link is dead

### ISSUE THREAD

**Issue by simonhughes22** [witheve/Eve#643]
The "core language" link http://docs.witheve.com/handbook/core-language on the bottom of http://docs.witheve.com/handbook/intro/ is a dead link.

**Comment by cmontella** [comment]
Fixed: https://github.com/witheve/docs/pull/37

The core language page is just blank right now though.... it's more of a header for the section, but it should have some meat to it. Going to track fixing that here: https://github.com/witheve/docs/issues/38
