### ISSUE TITLE
Expose a programmatic API for witheve npm module

### ISSUE THREAD

**Issue by fredhampton** [witheve/Eve#677]
I m trying to include Eve in as a node module in an app and for some reason when starting the app I receive the error message "Cannot find module 'witheve'"
I m using MacOS

The app works if I  do this   require('witheve/bin/eve.js') in my background-process.js files 
But throws the error when I do this   require('witheve')  in my background-process.js files 

I think that something is going on with the path to witheve which is    /Users/hampton/Desktop/douglass/app/node_modules/witheve

The full error message is as follows 

App threw an error during load
Error: Cannot find module 'witheve'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/hampton/Desktop/douglass/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at /Users/hampton/Desktop/douglass/app/background-process.build.js:4851:1
    at Object.<anonymous> (/Users/hampton/Desktop/douglass/app/background-process.build.js:4908:2)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)

Thanks so much for Eve !!!

**Comment by cmontella** [comment]
Just for clarity, could you let us know which versions of node/npm you are using?

```
node --version
npm --version
```

**Comment by fredhampton** [comment]
node --version
v7.2.0

npm --version
3.10.9


Thanks !!!!



On December 9, 2016 at 11:20:17 AM, Corey Montella (notifications@github.com) wrote:

Just for clarity, could you let us know which versions of node/npm you are using?

node --version
npm --version

**Comment by joshuafcole** [comment]
@fredhampton:

Sorry about the trouble. The NPM package doesn't currently expose a programmatic API. We intend to do this in the future. If you want to do a little reverse engineering take a look at what `bin/eve.js` does. You'll need to pull in the config module and correctly set it up and then call run on the server module.

**Comment by cmontella** [comment]
I changed the name of this issue to reflect Josh's answer. We can track the status of the npm module API here.

**Comment by fredhampton** [comment]
If i change this 
var internal = false; to var internal = ture 
in eve.js  it works but does not open the example page

seems to be something with the path ?

Thanks !!!

On December 9, 2016 at 1:04:19 PM, Joshua Cole (notifications@github.com) wrote:

@fredhampton:

Sorry about the trouble. The NPM package doesn't currently expose a programmatic API. We intend to do this in the future. If you want to do a little reverse engineering take a look at what bin/eve.js does. You'll need to pull in the config module and correctly set it up and then call run on the server module.

**Comment by cmontella** [comment]
The Eve node module now provides a JavaScript DSL in v0.3, so you can include Eve in your project like so

```
import {Program} from "witheve";
```
