### ISSUE TITLE
Need a way to set focus on an element

### ISSUE THREAD

**Issue by cmontella** [witheve/Eve#681]

**Comment by ibdknox** [comment]
autofocus only technically applies when the page is first loaded:

> This Boolean attribute lets you specify that a form control should have input focus when the page loads, unless the user overrides it, for example by typing in a different control.

From: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

**Comment by cmontella** [comment]
Okay, so if it's behaving as intended, we need a way to set focus arbitrarily. Changing name to reflect this.

**Comment by joshuafcole** [comment]
This is fixed in 0.3.
