### ISSUE TITLE
running eve takes me to the editor instead of examples page 

### ISSUE THREAD

**Issue by fredhampton** [witheve/Eve#684]
I have Eve running inside of a subdirectory.  When I start Eve the "root" shows with the editor.
Is there a way to have the example page load instead of the root with just the editor ?

![witheve-root](https://cloud.githubusercontent.com/assets/17618174/21085379/39116f3c-bfc6-11e6-8367-1058b6fdfd34.jpg)

Thanks !!!

**Comment by joshuafcole** [comment]
Hey Fred,

When you're running in a project directory (that is, a directory containing a `project.json` file) it will only show you the Eve files in your current workspace. (the directory containing the `project.json` file and its subdirectories). This is intended so users trying to build more serious programs don't have to constantly slog through the examples to get to their code. If you run the `eve` program outside of a project directory it should still give you the old examples workspace. :)

If you're having any other issues or would like to discuss this behavior please feel free to re-open!
