### ISSUE TITLE
Input value not dynamically updating

### ISSUE THREAD

**Issue by cakenggt** [witheve/Eve#717]
I am trying to recreate the todo example using the following gist. In this gist, if you enter text into the input it does create a new todo. However, it does not clear the input box.

This was tested in chrome Version 55.0.2883.87 m. It doesn't appear to work on firefox either.

https://gist.githubusercontent.com/anonymous/710df37a0e9706193ee9198519595d5e

I am seeing in the inspector that it is clearing the value of the input in the html, but this does not seem to dynamically set the value on the page. If you update the last line where it sets the input.value to `input.value := none`, it will successfully clear the input value.

**Comment by cmontella** [comment]
Thanks for bringing this up. We noted this issue before here: https://github.com/witheve/Eve/issues/658

I'll close the current issue so progress can be tracked in #658
