### ISSUE TITLE
Events related question

### ISSUE THREAD

**Issue by massanchik** [witheve/Eve#726]
Is #mousedown, #mousemove etc. events not working yet?
Working:
```
search @event
  [#click]
commit @browser
  [#div text: "triggered"]
```
Not working:
```
search @event
  [#mousedown]
commit @browser
  [#div text: "triggered"]
```

And one more question. 
How about function creation? Is there any syntax for that?
Or how to handle repeated operations? 
Get input and return calculated output... like that.

I'm actually added mousedown & mouseup handlers. 
Take a look:
https://github.com/massanchik/Eve/commit/9a5e530654f918f2fee79a5f70b1a163e8bd23bd

**Comment by Cormac-Williams** [comment]
Hi massanchik,

There's also an EVE file in the examples folder called event.eve (All of the databases have an EVE file for doing bits and pieces). This file has a block that removes events from the event database after they are posted, this means that an event is only available for one tick. I suspect this block will also need to be changed to prevent your new events hanging around on a permanent basis.

Note, I haven't tested your code to see whether this is the case, so could well be wrong about this.
 
Regards,
Cormac.

**Comment by cmontella** [comment]
@massanchik do you want to submit this as a PR? Otherwise I can do so.

**Comment by ibdknox** [comment]
Already was and already accepted :) https://github.com/witheve/Eve/pull/727
