### ISSUE TITLE
CSS libs integration

### ISSUE THREAD

**Issue by wilk** [witheve/Eve#734]
This issue is derived from https://github.com/witheve/Eve/issues/729

I tried to include a whole library like [bulma](http://bulma.io/) but it changed the entire IDE layout and style: https://gist.github.com/anonymous/421dd499f02a4b3d2d35e0589f4ec06c
Is there a way to add a CSS libs without breaking the IDE?

A proposal can be wrapping the IDE preview section into an iframe, isolating the CSS of the application from the IDE.

Others suggestions?

**Comment by cmontella** [comment]
Yeah, I think an iframe is the way to go here. Did you want to take up this project yourself?

**Comment by wilk** [comment]
@cmontella 

Yeah, I'm working on it ;)
Thanks!

**Comment by cmontella** [comment]
Great, keep us posted!
