### ISSUE TITLE
Unicode symbols as attributes.

### ISSUE THREAD

**Issue by Cormac-Williams** [witheve/Eve#739]
When playing with issues around attributes I noticed that we may be running into a minor issue if the use of unicode symbols as attribute names continues.

This was with the gaussian function μ symbol, which apparently has multiple unicode symbols which do not compare directly.

Best way to solve would be either to change the attribute names to a textual equivalent
or to add all variants to the AttributeMapping file and handle with extra code in the constraint.

Regards,
Cormac.

**Comment by cmontella** [comment]
I think the way to go here is keep it simple and change the attribute name to regular text. Using μ was a cool demonstration of unicode support in a function, but it's not very easy to type in the current editor. I think these attributes should be "mean" and "stdev" as they are commonly called.

**Comment by Cormac-Williams** [comment]
Pull request in.
