### ISSUE TITLE
Eve applications: how to ship them?

### ISSUE THREAD

**Issue by wilk** [witheve/Eve#767]
Hi,

I don't understand how to ship an Eve application out of the Eve platform: is it possible? If so, how?
AFAIK, Eve is interpreted but in a production environment a Javascript+HTML+CSS application is needed.
What about compile Eve instead? Does it make sense?

Wilk

**Comment by joshuafcole** [comment]
Hey @wilk,

Sorry about the unacceptably slow response. We've had our heads down on the refactor and it's required a whole lot of man hours and brain power.

While Eve is, as you say, interpreted. The current (and future) Eve runtimes all have executor implementations for JS, meaning that you can execute Eve entirely clientside. In fact, play.witheve.com does exactly this to help us keep server costs manageable. 

The Eve binary is also equipped with an executor that can run in node. This is slightly faster and enables multi-user database sharing (which can't be done in-browser without some central server), but you can still run in browser if you like (turning the binary into a dumb read/write file-server) with the `--localRuntime` flag.

By combining this with custom project support, you can keep your code in git and deploy single-page app style programs pretty easily. The actual UX that supports this will be receiving some love once we've finished the newly documented and more performant runtime implementation.

If you have any other questions or thoughts, please don't hesitate to bring them up in the mailing list [1]!

[1] https://groups.google.com/forum/#!forum/eve-talk

**Comment by wilk** [comment]
Thanks for the response: let's continue the discussion here -> https://groups.google.com/forum/#!forum/eve-talk
