### ISSUE TITLE
Keybindings

### ISSUE THREAD

**Issue by christopherdumas** [witheve/Eve#803]
Hypothetically, would it be against Eve's philosophy to provide VI or Emacs keybindings? I realized its a bit early for this, considering so much work still has to be done, but as a longtime VI user, I find it hard to navigate Eve's IDE without accidentally inserting an `h` or `j` here and there.

**Comment by joshuafcole** [comment]
We have no problem having support for these, and (for a quick
approximation, anyway) they're quick and easy to asd through the existing
codemirror emacs and vim addons. I used the emacs addon myself during
development. It just requires a bit of work to build a proper preferences
pane for the editor, which I was putting off until we had more than one
setting. ;) Another approach I considered was letting the user customize
their editor through an eve file. A simple watcher can translate from the
facts the user creates to options on the editor's code mirror inatance. The
old watcher interface was very clunky and tightly coupled to the runtime
internals, but that could be thrown together pretty quickly with the new
watcher setup.

**Comment by christopherdumas** [comment]
Nice. This is a little bit ahead of where Eve is, but its nice to hear!
