### ISSUE TITLE
No Start Script in Master 

### ISSUE THREAD

**Issue by fredhampton** [witheve/Eve#820]
There seems to be in Start Script in Master ?
I have been using and showing Eve to young (High School) students.
The version that I used has all of the examples and documentation and this makes it very easy for young programmer to begin to understand and use. 
The Starter branch seems to be not be geared towards beginners.
Having the Documentation as part of the code was Great !!!
Is the plan to not have the Documentation as part of the Dev interface ?
Is there a version of witheve that has the Start Script and the interface that allows for developing the code and the documentation with it ?

**Comment by joshuafcole** [comment]
Hey @fredhampton,

Sorry about the trouble. We've reorganized our github repository. The current stable branch (which has the editor you've been using) is now [here](https://github.com/witheve/eve/tree/release). You can also permanently link to any version of Eve using our version tags, e.g.: [v0.2.3](https://github.com/witheve/Eve/tree/v0.2.3). Additionally, the `witheve` npm package will always point to the latest stable version of Eve.

The master branch is now where our active development happens, so what you're currently seeing is a prerelease version of v0.3.0. While it has a lot of very important improvements for using Eve to build non-trivial programs ([performance](http://incidentalcomplexity.com/2017/03/08/february/#performance) and [extensibility](http://incidentalcomplexity.com/2017/03/08/february/#watchers) chief among them), it's still missing a lot of the features that made it easy to jump in and start working with. Having documentation interleaved with code is one of those features that hasn't been rebuilt yet but is definitely on the way.

We don't plan to make 0.3.0 the stable version until we've remedied that. :) If you have any specific comments or requests we'd love to talk them over with you on the [mailing list](https://groups.google.com/forum/#!forum/eve-talk).

**Comment by fredhampton** [comment]
Thanks !!!!
