### ISSUE TITLE
Problem with nested columns

### ISSUE THREAD

**Issue by smarks159** [witheve/Eve#829]
I am trying to specify a top level layout using flexbox, however when I have nested columns they don't seem to be rendering properly.

Run the following program in eve-starter

```javascript
import {Program} from "witheve";

let prog = new Program("Test Program");
prog.attach("ui");

prog.commit("main presenter",({record,find})=>{
    return [
        record("ui/column","parent column",{style:record({flex:1}),children:[
            record("ui/column","child column1",{style:record({flex:1})}),
            record("ui/column","child column2",{style:record({flex:1})})
        ]})
    ]
})

prog.inputEAVs([
  [1, "tag", "turtle"]
]);
```
This program produces the following html

```html
<column instance="344" element="340" tag="parent column" style="flex: 1 1 0%;">
    <column instance="345" element="338"></column>
    <column instance="346" element="339"></column>
</column>
```

The tag and style attributes are missing from the child columns.

This happens in both firefox and chrome

**Comment by smarks159** [comment]
The problem with the code above turned out to be tags with spaces in them. The following code works as expected:

```javascript
import {Program} from "witheve";

let prog = new Program("Test Program");
prog.attach("ui");

prog.commit("main presenter",({record,find})=>{
    return [
        record("ui/column","parent_column",{style:record({flex:1}),children:[
            record("ui/column","child_column1",{style:record({flex:1})}),
            record("ui/column","child_column2",{style:record({flex:1})})
        ]})
    ]
})

prog.inputEAVs([
  [1, "tag", "turtle"]
]);
```

**Comment by smarks159** [comment]
this has been fixed in the latest version of eve

**Comment by joshuafcole** [comment]
@smarks159 
Sorry for not responding here, it slipped through the cracks. The issue was that we hadn't expected tags to have spaces in them, like you said. We've made the system more robust now, so that hopefully shouldn't be a problem going forward. Note that we still recommend against it, because that doesn't translate well into the native Eve syntax.
