### ISSUE TITLE
Links at http://play.witheve.com/#/examples/quickstart.eve are broken

### ISSUE THREAD

**Issue by chasets** [witheve/Eve#837]
The links at http://play.witheve.com/#/examples/quickstart.eve are broken. For example, the first link for "record" points to https://witheve.github.io/docs/handbook/records/. This gets redirected to http://docs.witheve.com/handbook/records/, which is not found. Same for other links on the page.

**Comment by joshuafcole** [comment]
Thank you for reporting this, @chasets. It slipped under our radar when we updated the documentation for 0.3. We will cut a new release of 0.2 with fixed quickstart links and push them to npm and play.witheve.com soon.

**Comment by joshuafcole** [comment]
This is now fixed on the release branch, and we're pushing v0.2.5 to npm and play.witheve.com to address this in situ.
