### ISSUE TITLE
Parser exception on missing close quote

### ISSUE THREAD

**Issue by btheado** [witheve/Eve#852]
When a quote is missing like this:

```
bind
  [#ui/div text: "missing quote]
```

a parser exception like "Cannot read property 'length' of undefined" results

**Comment by joshuafcole** [comment]
This should be fixed by: https://github.com/witheve/Eve/pull/848. You can build a local copy of eve by:
```
$ git clone https://github.com/witheve/Eve.git
$ cd Eve
$ npm install
$ npm pack
$ ls
```
From ls, find the name of the new `witheve-<version>.tar.gz` file generated, and then update your project to use it by:

```
$ cd path/to/project-directory
$ npm install path/to/witheve-<version>.tar.gz
```

**Comment by btheado** [comment]
Thanks. I no longer get parser exception for this case.
