### ISSUE TITLE
TodoMVC Example Suggestion (Eve Alpha v0.2.3)

### ISSUE THREAD

**Issue by nayrpg** [witheve/Eve#865]
Create an embedded css line that moves the text box past the checkbox. This way the page looks nicer and you get to show off the inline css feature in the example

With CSS Block
![image](https://user-images.githubusercontent.com/11809432/27707988-48689fa2-5ce5-11e7-8f79-fb91ad60ec4a.png)

Without CSS Block
![image](https://user-images.githubusercontent.com/11809432/27708117-cf042c02-5ce5-11e7-97c1-4ad66107e011.png)

**Comment by joshuafcole** [comment]
Hey @nayrpg,

We've actually just pushed a fix addressing this problem. Thanks for the feedback and please let us know if you have any other ideas on how to improve Eve!
