### ISSUE TITLE
Change "hidden" tables/views to "system" tables

### ISSUE THREAD

**Issue by joshuafcole** [witheve/Eve#96]

**Comment by jakedowns** [comment]
Is this still desired? Would you like the localStorage item name changed to `showSystem` as well?

**Comment by jakedowns** [comment]
Also, would "show system tables" be better for the button title? or just "show system"
![](https://s3.amazonaws.com/f.cl.ly/items/0M2T1I2A3j3N1t3O2T1l/Image%202015-10-29%20at%207.19.52%20PM.png)

**Comment by cmontella** [comment]
Yes, this is still something we want to do. I

**Comment by jakedowns** [comment]
@cmontella Cool, thanks for the reply! Let me know if I missed anything in my PR, but the visibility toggle and item count are updating on my local copy

**Comment by cmontella** [comment]
NP, we'll merge it in once we have a look at it. Thanks for the help!
